# 5. Grouping & Aggregation

idxmax(),idxmin():give me the index(row/label)of the maximum value in this series or dataframe.

In [1]:
# 1.groupby()

# Used to split data into groups and apply functions(mean,sum,count,etc)

import pandas as pd

df=pd.DataFrame({
    "Department":["IT","IT","HR","HR","Sales"],
    "Salary":[50000,60000,45000,47000,55000]
})

# Average Salary per department

print(df.groupby('Department')['Salary'].mean())

Department
HR       46000.0
IT       55000.0
Sales    55000.0
Name: Salary, dtype: float64

In [2]:
# 2. Multiple Aggregations(agg()):many functions at once.

df.groupby("Department")["Salary"].agg(['mean','sum','count'])

               mean     sum  count
Department
HR          46000.0   92000      2
IT          55000.0  110000      2
Sales       55000.0   55000      1

In [3]:
# 3. Pivot Table:summary table 

print(df)
pd.pivot_table(df,values='Salary',index='Department',aggfunc='mean')

  Department  Salary
0         IT   50000
1         IT   60000
2         HR   45000
3         HR   47000
4      Sales   55000

            Salary
Department
HR           46000
IT           55000
Sales        55000

In [5]:
# 4. Crosstab: compare categories (like gender vs department)

# for categorical data comparision.

df2=pd.DataFrame({
    "Gender":['M','F','M','F','M'],
    "Department":['IT','HR','IT','Sales','HR']
})

pd.crosstab(df2['Gender'],df2['Department'])

Department  HR  IT  Sales
Gender
F            1   0      1
M            1   2      0

# Practice Questions:-

Task-1: Student Marks

data={
    "Class":[10,10,10,11,11,12,12],
    "Student":["Rahul","Aman","Priya","Sneha","Kiran","Meena","Raju"],
    "Subject":["Math","English","Math","English","Math","English","Math"],
    "Marks":[88,75,92,85,80,90,70]
}

->Find Average marks per class.

->Find highest marks per subject.

->Count how many students are in each class.

->Create a pivote table:Class Vs Subject with average marks.



Task-2:Online Store Orders

data={
    "OrderID Quantity":[1,5,2,2,3,1,4,3,5,2,6,1],
    "Product":["Pen","Book","Laptop","Mouse","Shirt","Jeans"],
    "Category":["Stationery","Stationery","Electronics","Electronics","Clothing","Clothing"],
    "Price":[10,100,50000,1000,700,1200]
}

->Find total sales(Price*Quantity) for each category.

->Find average price per category.

->Use agg() to calculate min,max and mean price per category.

->Pivot table: Category Vs Product->total sales.



Task-3: Employees data


data={
    "Dept":["IT","IT","HR","HR","Sales","Sales","Sales"],
    "Gender":["M","F","F","M","M","F","M"],
    "Experience":[2,5,3,4,6,2,8],
    "Salary":[40000,60000,45000,48000,55000,52000,70000]
}

->Find average salary per department.

->Find total salary of Male Vs Female employees.

->Crosstab->Gender Vs Department.

->Find Average experience per department.



Task-4: Movie Ratings


data={
    "Movie":["Inception","Inception","Titanic","Titanic","Avengers","Avengers"],
    "Genre":["Sci-Fi","Sci-Fi","Romance","Romance","Action","Action"],
    "User":["U1","U2","U3","U4","U5","U6"],
    "Rating":[9,8,9,7,8,9]
}


->Find average rating per genre.

->Count how many ratings each movie received.

->Which genre got the highest average rating?

->Pivot table: Genre Vs Movie->average rating.




Task-5: Sales by region


data={
    "Region":["North","North","South","South","East","East"],
    "Salesman":["Ramesh","Suresh","Raj","Meena","Aman","Sneha"],
    "Product":["Pen","Book","Pen","Book","Pen","Bag"],
    "Sales":[200,300,150,250,180,400]
}

->Find total sales per region.

->Find total sales per product.

->Pivot table: Region Vs Product-> total sales.

->Crosstab: Region Vs Salesman->count of sales records.


----------------------------------------------------------------------------------------------------------

# Task-1: Student Marks

In [54]:
data={ 
    "Class":[10,10,10,11,11,12,12], 
    "Student":["Rahul","Aman","Priya","Sneha","Kiran","Meena","Raju"], 
    "Subject":["Math","English","Math","English","Math","English","Math"], 
    "Marks":[88,75,92,85,80,90,70] 
}

df =pd.DataFrame(data)

print(df)

   Class Student  Subject  Marks
0     10   Rahul     Math     88
1     10    Aman  English     75
2     10   Priya     Math     92
3     11   Sneha  English     85
4     11   Kiran     Math     80
5     12   Meena  English     90
6     12    Raju     Math     70

In [55]:
# ->Find Average marks per class.

print(df.groupby("Class")["Marks"].mean())

Class
10    85.0
11    82.5
12    80.0
Name: Marks, dtype: float64

In [56]:
# ->Find highest marks per subject.

print(df.groupby("Subject")["Marks"].max())

Subject
English    90
Math       92
Name: Marks, dtype: int64

In [57]:
# ->Count how many students are in each class.

print(df.groupby("Class")["Student"].count())

Class
10    3
11    2
12    2
Name: Student, dtype: int64

In [58]:
# ->Create a pivote table:Class Vs Subject with average marks.

print(df)

pd.pivot_table(df,values="Class",index = "Subject",aggfunc = "mean")

# pivot = pd.pivot_table(
#     df,
#     values="Marks",
#     index="Class",
#     columns="Subject",
#     aggfunc="mean"
# )

# print(pivot)

   Class Student  Subject  Marks
0     10   Rahul     Math     88
1     10    Aman  English     75
2     10   Priya     Math     92
3     11   Sneha  English     85
4     11   Kiran     Math     80
5     12   Meena  English     90
6     12    Raju     Math     70

         Class
Subject
English  11.00
Math     10.75

# Task-2:Online Store Orders

In [59]:
import pandas as pd

data={ 
    "OrderID":[1,2,3,4,5,6],
    "Quantity":[5,2,2,3,1,4],
    "Product":["Pen","Book","Laptop","Mouse","Shirt","Jeans"], 
    "Category":["Stationery","Stationery","Electronics","Electronics","Clothing","Clothing"], 
    "Price":[10,100,50000,1000,700,1200] 
}

df = pd.DataFrame(data)
print(df)

   OrderID  Quantity Product     Category  Price
0        1         5     Pen   Stationery     10
1        2         2    Book   Stationery    100
2        3         2  Laptop  Electronics  50000
3        4         3   Mouse  Electronics   1000
4        5         1   Shirt     Clothing    700
5        6         4   Jeans     Clothing   1200

In [60]:
# ->Find total sales(Price*Quantity) for each category.

df["Sales"] = df["Price"] * df["Quantity"]

total_sales = df.groupby("Category")["Sales"].sum()

print(total_sales)

Category
Clothing         5500
Electronics    103000
Stationery        250
Name: Sales, dtype: int64

In [61]:
# ->Find average price per category.

print(df.groupby("Category")["Price"].mean())

Category
Clothing         950.0
Electronics    25500.0
Stationery        55.0
Name: Price, dtype: float64

In [62]:
# ->Use agg() to calculate min,max and mean price per category.

print(df)
df.groupby("Category")["Price"].agg(["min","max","mean"])

   OrderID  Quantity Product     Category  Price   Sales
0        1         5     Pen   Stationery     10      50
1        2         2    Book   Stationery    100     200
2        3         2  Laptop  Electronics  50000  100000
3        4         3   Mouse  Electronics   1000    3000
4        5         1   Shirt     Clothing    700     700
5        6         4   Jeans     Clothing   1200    4800

              min    max     mean
Category
Clothing      700   1200    950.0
Electronics  1000  50000  25500.0
Stationery     10    100     55.0

In [63]:
# ->Pivot table: Category Vs Product->total sales.

print(pd.pivot_table(df,
                     values = "Category",
                     index = "Product", 
                     aggfunc = "sum"
                    )
     )

print("-------------")
pivot = pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)

print(pivot)

            Category
Product
Book      Stationery
Jeans       Clothing
Laptop   Electronics
Mouse    Electronics
Pen       Stationery
Shirt       Clothing
-------------
Product      Book  Jeans  Laptop  Mouse  Pen  Shirt
Category
Clothing        0   4800       0      0    0    700
Electronics     0      0  100000   3000    0      0
Stationery    200      0       0      0   50      0

# Task-3: Employees data

In [65]:
data={ 
    "Dept":["IT","IT","HR","HR","Sales","Sales","Sales"], 
    "Gender":["M","F","F","M","M","F","M"], 
    "Experience":[2,5,3,4,6,2,8], 
    "Salary":[40000,60000,45000,48000,55000,52000,70000] 
}

df = pd.DataFrame(data)
print(df)

    Dept Gender  Experience  Salary
0     IT      M           2   40000
1     IT      F           5   60000
2     HR      F           3   45000
3     HR      M           4   48000
4  Sales      M           6   55000
5  Sales      F           2   52000
6  Sales      M           8   70000

In [66]:
# ->Find average salary per department.

print(df.groupby("Dept")["Salary"].mean())

Dept
HR       46500.0
IT       50000.0
Sales    59000.0
Name: Salary, dtype: float64

In [67]:
# ->Find total salary of Male Vs Female employees.

print(df.groupby("Gender")["Salary"].sum())

Gender
F    157000
M    213000
Name: Salary, dtype: int64

In [69]:
# ->Crosstab->Gender Vs Department.

pd.crosstab(df["Gender"],df["Dept"])

Dept    HR  IT  Sales
Gender
F        1   1      1
M        1   1      2

In [71]:
# ->Find Average experience per department

df.groupby("Dept")["Experience"].mean()

Dept
HR       3.500000
IT       3.500000
Sales    5.333333
Name: Experience, dtype: float64

# Task-4: Movie Ratings

In [75]:
data={ 
    "Movie":["Inception","Inception","Titanic","Titanic","Avengers","Avengers"], 
    "Genre":["Sci-Fi","Sci-Fi","Romance","Romance","Action","Action"], 
    "User":["U1","U2","U3","U4","U5","U6"], 
    "Rating":[9,8,9,7,8,9] 
}

df = pd.DataFrame(data)

df

       Movie    Genre User  Rating
0  Inception   Sci-Fi   U1       9
1  Inception   Sci-Fi   U2       8
2    Titanic  Romance   U3       9
3    Titanic  Romance   U4       7
4   Avengers   Action   U5       8
5   Avengers   Action   U6       9

In [76]:
# ->Find average rating per genre.

df.groupby("Genre")["Rating"].mean()

Genre
Action     8.5
Romance    8.0
Sci-Fi     8.5
Name: Rating, dtype: float64

In [77]:
# ->Count how many ratings each movie received.

df.groupby("Movie")["Rating"].count()

Movie
Avengers     2
Inception    2
Titanic      2
Name: Rating, dtype: int64

In [82]:
# ->Which genre got the highest average rating?

highest_genre = df.groupby("Genre")["Rating"].mean().idxmax()
print(highest_genre)

Action

In [83]:
# ->Pivot table: Genre Vs Movie->average rating.

pd.pivot_table(df,values = "Rating",index = "Genre", columns = "Movie",aggfunc = "mean")

Movie    Avengers  Inception  Titanic
Genre
Action        8.5        NaN      NaN
Romance       NaN        NaN      8.0
Sci-Fi        NaN        8.5      NaN

# Task-5: Sales by region

In [84]:
data={ 
    "Region":["North","North","South","South","East","East"], 
    "Salesman":["Ramesh","Suresh","Raj","Meena","Aman","Sneha"], 
    "Product":["Pen","Book","Pen","Book","Pen","Bag"], 
    "Sales":[200,300,150,250,180,400] 
}

df = pd.DataFrame(data)

df

  Region Salesman Product  Sales
0  North   Ramesh     Pen    200
1  North   Suresh    Book    300
2  South      Raj     Pen    150
3  South    Meena    Book    250
4   East     Aman     Pen    180
5   East    Sneha     Bag    400

In [87]:
# ->Find total sales per region.

df.groupby("Region")["Sales"].sum()

Region
East     580
North    500
South    400
Name: Sales, dtype: int64

In [89]:
# ->Find total sales per product.

df.groupby("Product")["Sales"].sum()

Product
Bag     400
Book    550
Pen     530
Name: Sales, dtype: int64

In [90]:
# ->Pivot table: Region Vs Product-> total sales.

pd.pivot_table(df,values = "Sales", index = "Region", columns = "Product",aggfunc = "sum")

Product    Bag   Book    Pen
Region
East     400.0    NaN  180.0
North      NaN  300.0  200.0
South      NaN  250.0  150.0

In [91]:
# ->Crosstab: Region Vs Salesman->count of sales records.

pd.crosstab(df["Region"],df["Salesman"])

Salesman  Aman  Meena  Raj  Ramesh  Sneha  Suresh
Region
East         1      0    0       0      1       0
North        0      0    0       1      0       1
South        0      1    1       0      0       0