# 8.Working with Dates and Time

1.Converting to DateTime:- Pandas me dates by default string ("2025-01-15") ke form me hote hai.unhe datetime object banana padta hai,taki hum unse year, month,day resampling kar saken.

In [122]:
import pandas as pd

data={
    "Order ID":[101,102,103,104,105],
    "OrderDate":["2025-01-15","2025-02-20","2025-03-05","2025-03-18","2025-04-28"],
    "Sales":[250,300,400,200,350]
}

df=pd.DataFrame(data)
df.dtypes
# # Convert to datetime
df['OrderDate']=pd.to_datetime(df['OrderDate'])

print(df.dtypes)

# Output me OrderDate ka dtype datetime64[ns] hojayega

Order ID              int64
OrderDate    datetime64[ns]
Sales                 int64
dtype: object

2.Extracting year,month,day

In [123]:
df['Year']=df['OrderDate'].dt.year
df['Month']=df['OrderDate'].dt.month
df['Day']=df['OrderDate'].dt.day
print(df)

   Order ID  OrderDate  Sales  Year  Month  Day
0       101 2025-01-15    250  2025      1   15
1       102 2025-02-20    300  2025      2   20
2       103 2025-03-05    400  2025      3    5
3       104 2025-03-18    200  2025      3   18
4       105 2025-04-28    350  2025      4   28

3.Resampling & Frequency Conversion

ye time-series ML me bahot use hota hai.Resampling ka matlab hai ek frequency se dusri frequency me data ko convert krna (daily->monthly,weekly->yearly).

In [124]:
# Index ko date banana pdta hai resampling ke liye
# df=df.set_index("OrderDate")

# # Monthly sales total
# monthly_sales=df['Sales'].resample("M").sum()
# print(monthly_sales)
# weekly sales total

weekly_sales=df['Sales'].resample("W").sum()
print(weekly_sales)

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

# Practice Questions (Dates & Time)

Q1. Datetime Conversion

You have a DataFrame:

data = {
    "CustomerID": [1,2,3,4,5],
    "JoinDate": ["2024-12-01","2025-01-10","2025-02-15","2025-02-28","2025-03-12"],
    "Purchase": [500,700,200,450,300]
}

👉 Tasks:

1. Convert JoinDate into datetime.


2. Check the dtype of JoinDate.




Q2. Extract Year, Month, Day

Using the same dataset above:

1. Create a new column JoinYear from the year of JoinDate.


2. Create a new column JoinMonth from the month.


3. Create a new column JoinDay from the day.





Q3. Monthly & Weekly Sales

You have this DataFrame:

data = {
    "OrderID": [201,202,203,204,205,206],
    "OrderDate": ["2025-01-02","2025-01-15","2025-01-29","2025-02-10","2025-02-25","2025-03-05"],
    "Amount": [120,250,300,500,150,400]
}

👉 Tasks:

1. Convert OrderDate to datetime and set it as the index.


2. Find monthly total sales.


3. Find weekly total sales.





Q4. Quarterly Analysis

You have stock price data:

data = {
    "Date": ["2025-01-10","2025-02-18","2025-03-25","2025-04-05","2025-04-20","2025-05-15"],
    "Price": [105,110,115,120,118,125]
}

👉 Tasks:

1. Convert Date into datetime and set it as index.


2. Calculate quarterly average price.





Q5.(Retail Store)

Suppose you are a retail store analyst. You have this dataset:

data = {
    "InvoiceID": [501,502,503,504,505,506,507],
    "InvoiceDate": ["2025-01-03","2025-01-12","2025-01-25","2025-02-08","2025-02-19","2025-03-02","2025-03-15"],
    "Revenue": [2000,1500,1800,2200,2500,1700,3000]
}

👉 Tasks:

1. Convert InvoiceDate to datetime.


2. Extract Year, Month, Day into new columns.


3. Find monthly total revenue.


4. Find weekly total revenue.


5. Find which month had the highest revenue.




----------------------------------------------------------------------------------------------------------

# Q1. Datetime Conversion

In [125]:
# You have a DataFrame:
import pandas as pd

data = { 
        "CustomerID": [1,2,3,4,5], 
        "JoinDate": ["2024-12-01","2025-01-10","2025-02-15","2025-02-28","2025-03-12"], 
        "Purchase": [500,700,200,450,300] 
}

df = pd.DataFrame(data)
print(df.dtypes)

CustomerID     int64
JoinDate      object
Purchase       int64
dtype: object

In [126]:
# 👉 Tasks:

# 1. Convert JoinDate into datetime.

df["JoinDate"] = pd.to_datetime(df["JoinDate"])

# 2. Check the dtype of JoinDate.

print(df.dtypes)
df

CustomerID             int64
JoinDate      datetime64[ns]
Purchase               int64
dtype: object

   CustomerID   JoinDate  Purchase
0           1 2024-12-01       500
1           2 2025-01-10       700
2           3 2025-02-15       200
3           4 2025-02-28       450
4           5 2025-03-12       300

# Q2. Extract Year, Month, Day

In [127]:
# Using the same dataset above:

# 1. Create a new column JoinYear from the year of JoinDate.

df["Year"] = df["JoinDate"].dt.year
df

   CustomerID   JoinDate  Purchase  Year
0           1 2024-12-01       500  2024
1           2 2025-01-10       700  2025
2           3 2025-02-15       200  2025
3           4 2025-02-28       450  2025
4           5 2025-03-12       300  2025

In [128]:
# 2. Create a new column JoinMonth from the month.

df["Month`"] = df["JoinDate"].dt.month
df

   CustomerID   JoinDate  Purchase  Year  Month`
0           1 2024-12-01       500  2024      12
1           2 2025-01-10       700  2025       1
2           3 2025-02-15       200  2025       2
3           4 2025-02-28       450  2025       2
4           5 2025-03-12       300  2025       3

In [129]:
# 3. Create a new column JoinDay from the day.

df["Day"] = df["JoinDate"].dt.day
df

   CustomerID   JoinDate  Purchase  Year  Month`  Day
0           1 2024-12-01       500  2024      12    1
1           2 2025-01-10       700  2025       1   10
2           3 2025-02-15       200  2025       2   15
3           4 2025-02-28       450  2025       2   28
4           5 2025-03-12       300  2025       3   12

# Q3. Monthly & Weekly Sales

In [130]:
# You have this DataFrame:

data = { 
        "OrderID": [201,202,203,204,205,206], 
        "OrderDate": ["2025-01-02","2025-01-15","2025-01-29","2025-02-10","2025-02-25","2025-03-05"], 
        "Amount": [120,250,300,500,150,400] 
}

df = pd.DataFrame(data)
print(df)

   OrderID   OrderDate  Amount
0      201  2025-01-02     120
1      202  2025-01-15     250
2      203  2025-01-29     300
3      204  2025-02-10     500
4      205  2025-02-25     150
5      206  2025-03-05     400

In [131]:
# 👉 Tasks:

# 1. Convert OrderDate to datetime and set it as the index.


df["OrderDate"] = pd.to_datetime(df["OrderDate"])

In [132]:

df.set_index("OrderDate",inplace = True)
df

            OrderID  Amount
OrderDate
2025-01-02      201     120
2025-01-15      202     250
2025-01-29      203     300
2025-02-10      204     500
2025-02-25      205     150
2025-03-05      206     400

In [133]:
# 2. Find monthly total sales.

monthly_sales = df["Amount"].resample("M").sum()
print(monthly_sales)

OrderDate
2025-01-31    670
2025-02-28    650
2025-03-31    400
Freq: M, Name: Amount, dtype: int64

In [134]:
# 3. Find weekly total sales.

weekly_sales = df["Amount"].resample("W").sum()
print(weekly_sales)

OrderDate
2025-01-05    120
2025-01-12      0
2025-01-19    250
2025-01-26      0
2025-02-02    300
2025-02-09      0
2025-02-16    500
2025-02-23      0
2025-03-02    150
2025-03-09    400
Freq: W-SUN, Name: Amount, dtype: int64

# Q4. Quarterly Analysis

In [141]:
# You have stock price data:

data = { 
        "Date": ["2025-01-10","2025-02-18","2025-03-25","2025-04-05","2025-04-20","2025-05-15"], 
        "Price": [105,110,115,120,118,125] 
}

df = pd.DataFrame(data)
print(df)

         Date  Price
0  2025-01-10    105
1  2025-02-18    110
2  2025-03-25    115
3  2025-04-05    120
4  2025-04-20    118
5  2025-05-15    125

In [142]:
# 👉 Tasks:

# 1. Convert Date into datetime and set it as index.

df["Date"] = pd.to_datetime(df["Date"])

In [143]:
df.set_index("Date", inplace = True)
df

            Price
Date
2025-01-10    105
2025-02-18    110
2025-03-25    115
2025-04-05    120
2025-04-20    118
2025-05-15    125

In [144]:
# 2. Calculate quarterly average price.

quarterly_avg = df["Price"].resample("Q").mean()
print(quarterly_avg)

Date
2025-03-31    110.0
2025-06-30    121.0
Freq: Q-DEC, Name: Price, dtype: float64

# Q5.(Retail Store)

In [172]:
# Suppose you are a retail store analyst. You have this dataset:

data = { 
        "InvoiceID": [501,502,503,504,505,506,507], 
        "InvoiceDate": ["2025-01-03","2025-01-12","2025-01-25","2025-02-08","2025-02-19","2025-03-02","2025-03-15"], 
        "Revenue": [2000,1500,1800,2200,2500,1700,3000] 
}

df = pd.DataFrame(data)
df.dtypes

InvoiceID       int64
InvoiceDate    object
Revenue         int64
dtype: object

In [173]:
# 👉 Tasks:

# 1. Convert InvoiceDate to datetime.


df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
print(df.dtypes)

df.set_index("InvoiceDate",inplace = True)
df

InvoiceID               int64
InvoiceDate    datetime64[ns]
Revenue                 int64
dtype: object

             InvoiceID  Revenue
InvoiceDate
2025-01-03         501     2000
2025-01-12         502     1500
2025-01-25         503     1800
2025-02-08         504     2200
2025-02-19         505     2500
2025-03-02         506     1700
2025-03-15         507     3000

In [174]:
# 2. Extract Year, Month, Day into new columns.

# df["Year"] = df["InvoiceDate"].dt.year
# df["month"] = df["InvoiceDate"].dt.month
df["day"] = df["InvoiceDate"].dt.day

df

KeyError: 'InvoiceDate'

In [165]:
# 3. Find monthly total revenue.

month_total_rev = df["Revenue"].resample("M").sum()
print(month_total_rev)

InvoiceDate
2025-01-31    5300
2025-02-28    4700
2025-03-31    4700
Freq: M, Name: Revenue, dtype: int64

In [166]:
# 4. Find weekly total revenue.

week_total_rev = df["Revenue"].resample("W").sum()
print(week_total_rev)

InvoiceDate
2025-01-05    2000
2025-01-12    1500
2025-01-19       0
2025-01-26    1800
2025-02-02       0
2025-02-09    2200
2025-02-16       0
2025-02-23    2500
2025-03-02    1700
2025-03-09       0
2025-03-16    3000
Freq: W-SUN, Name: Revenue, dtype: int64

In [167]:
# 5. Find which month had the highest revenue.

month_High_rev = df["Revenue"].resample("M").max()
print(month_High_rev)

InvoiceDate
2025-01-31    2000
2025-02-28    2500
2025-03-31    3000
Freq: M, Name: Revenue, dtype: int64