In [1]:
import pandas as pd

In [20]:
data = { 
        "Student": ["Aman", None, "Ranu", "Neha", "Tina", None], 
        "City": ["Delhi", "Mumbai", None, "Surat", None, "Pune"], 
        "Age": [18, 19, None, 20, None, 21], 
        "Python": [85, None, 70, 90, None, 75], 
        "Django": [88, 80, None, None, 92, 85], 
        "Attendance": [None, 80, 95, None, 85, 90] 
}

df = pd.DataFrame(data)

df

  Student    City   Age  Python  Django  Attendance
0    Aman   Delhi  18.0    85.0    88.0         NaN
1    None  Mumbai  19.0     NaN    80.0        80.0
2    Ranu    None   NaN    70.0     NaN        95.0
3    Neha   Surat  20.0    90.0     NaN         NaN
4    Tina    None   NaN     NaN    92.0        85.0
5    None    Pune  21.0    75.0    85.0        90.0

# Task 1 — Show Which Values Are Missing 
Use: 
df.isnull()

In [21]:
df.isnull()

   Student   City    Age  Python  Django  Attendance
0    False  False  False   False   False        True
1     True  False  False    True   False       False
2    False   True   True   False    True       False
3    False  False  False   False    True        True
4    False   True   True    True   False       False
5     True  False  False   False   False       False

# Task 2 — Count Missing Values Column-wise 
Use: 
df.isnull().sum()

In [22]:
df.isnull().sum()

Student       2
City          2
Age           2
Python        2
Django        2
Attendance    2
dtype: int64

# Task 3 — Count Total Missing Values 
Count total NaN in entire dataset.

In [23]:
df.isnull().sum().sum()

12

# Task 4 — Remove All Rows Containing NaN 
Use: 
df.dropna()

In [24]:
df.dropna()

Empty DataFrame
Columns: [Student, City, Age, Python, Django, Attendance]
Index: []

# Task 5 — Remove All Columns Containing NaN 
Use: 
df.dropna(axis=1)

In [25]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

# Task 6 — Fill Missing Values With 0 
Use: 
df.fillna(0)

In [26]:
df.fillna(0)

  Student    City   Age  Python  Django  Attendance
0    Aman   Delhi  18.0    85.0    88.0         0.0
1       0  Mumbai  19.0     0.0    80.0        80.0
2    Ranu       0   0.0    70.0     0.0        95.0
3    Neha   Surat  20.0    90.0     0.0         0.0
4    Tina       0   0.0     0.0    92.0        85.0
5       0    Pune  21.0    75.0    85.0        90.0

# Task 7 — Fill Age Column With Mean 
Replace missing Age with: 
df["Age"].fillna(df["Age"].mean())

In [28]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

  Student    City   Age  Python  Django  Attendance
0    Aman   Delhi  18.0    85.0    88.0         NaN
1    None  Mumbai  19.0     NaN    80.0        80.0
2    Ranu    None  19.5    70.0     NaN        95.0
3    Neha   Surat  20.0    90.0     NaN         NaN
4    Tina    None  19.5     NaN    92.0        85.0
5    None    Pune  21.0    75.0    85.0        90.0

# Task 8 — Fill Python Marks With Median 
Use: 
df["Python"].fillna(df["Python"].median())

In [29]:
df["Python"] = df["Python"].fillna(df["Python"].median())

df

  Student    City   Age  Python  Django  Attendance
0    Aman   Delhi  18.0    85.0    88.0         NaN
1    None  Mumbai  19.0    80.0    80.0        80.0
2    Ranu    None  19.5    70.0     NaN        95.0
3    Neha   Surat  20.0    90.0     NaN         NaN
4    Tina    None  19.5    80.0    92.0        85.0
5    None    Pune  21.0    75.0    85.0        90.0

# Task 9 — Fill Missing Student Names With "Unknown" 
Use: 
df["Student"].fillna("Unknown")

In [30]:
df["Student"] = df["Student"].fillna("Unknown")

df

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0         NaN
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu    None  19.5    70.0     NaN        95.0
3     Neha   Surat  20.0    90.0     NaN         NaN
4     Tina    None  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0

# Task 10 — Forward Fill 
Use: 
df.fillna(method='ffill')

In [31]:
df = df.fillna(method='ffill')
df

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0         NaN
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu  Mumbai  19.5    70.0    80.0        95.0
3     Neha   Surat  20.0    90.0    80.0        95.0
4     Tina   Surat  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0

# Task 11 — Backward Fill 
Use: 
df.fillna(method='bfill')

In [32]:
df = df.fillna(method='bfill')
df

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0        80.0
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu  Mumbai  19.5    70.0    80.0        95.0
3     Neha   Surat  20.0    90.0    80.0        95.0
4     Tina   Surat  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0

# Task 12 — Conditional Fill (Attendance) 
If Attendance is missing → fill 75

In [35]:
df.loc[df["Attendance"].isna(),"Attendance"] = 75
df

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0        80.0
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu  Mumbai  19.5    70.0    80.0        95.0
3     Neha   Surat  20.0    90.0    80.0        95.0
4     Tina   Surat  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0

# Task 13 — Conditional Fill (City) 
If City missing → fill with "Unknown City"

In [38]:
df.loc[df["City"].isna(),"City"] = "Unknown City" 
df

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0        80.0
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu  Mumbai  19.5    70.0    80.0        95.0
3     Neha   Surat  20.0    90.0    80.0        95.0
4     Tina   Surat  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0

# Task 14 — Different Rules for Different Column

In [40]:
rules = {
        "Student": "Unknown",
        "City": "Unknown City",
        "Age": df["Age"].mean(),
        "Python": df["Python"].median(),
        "Django": df["Django"].mean(),
        "Attendance": 75
    }

df = df.fillna(rules)

print(df)

   Student    City   Age  Python  Django  Attendance
0     Aman   Delhi  18.0    85.0    88.0        80.0
1  Unknown  Mumbai  19.0    80.0    80.0        80.0
2     Ranu  Mumbai  19.5    70.0    80.0        95.0
3     Neha   Surat  20.0    90.0    80.0        95.0
4     Tina   Surat  19.5    80.0    92.0        85.0
5  Unknown    Pune  21.0    75.0    85.0        90.0