# 1.Pandas Basics




What is Pandas?

Pandas is a python library used for working with data sets.

it has function for analyzing,cleaning,exploring and manipulating data.

the name "Pandas" has a reference to both "Panel Data" and Python Data Analysis" and was created by Wes mckinney in 2008.


Why Use Pandas?

Pandas allows us to analyze big data and make conclusions based on statical theories.

pandas can clean messy data sets, and make them readable and relevant.

Relevant data is very important in data science.


What Can Pandas Do?

Pandas gives you answer about the data.

Like:

->is there a correlation between two or more columns?

->what is average value.

->max value?

->min value?


Pandas are also able to delete rows that are not relevant, or contains wrong values , like empty or NULL values. This is called cleaning the data.

In [7]:
import pandas as pd

a =[1,2,3,4,5,6,7]
i = ['a','b','c','d','e','f','g']

s = pd.Series(a,index=i)

print(s)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [8]:
import pandas as pd

data = {
    'name':['kuldip','sumit','ankit'],
    'age':[21,32,23]
}

df =pd.DataFrame(data)

df['marks'] = [54,None,66]

df.dropna(axis=1)

     name  age
0  kuldip   21
1   sumit   32
2   ankit   23

In [9]:
import pandas as pd

df = pd.read_csv('Employee.csv')

df.head()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,198,Donald,OConnell,DOCONNEL,650.507.9833,21-JUN-07,SH_CLERK,2600,-,124,50
1,199,Douglas,Grant,DGRANT,650.507.9844,13-JAN-08,SH_CLERK,2600,-,124,50
2,200,Jennifer,Whalen,JWHALEN,515.123.4444,17-SEP-03,AD_ASST,4400,-,101,10
3,201,Michael,Hartstein,MHARTSTE,515.123.5555,17-FEB-04,MK_MAN,13000,-,100,20
4,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,-,201,20

In [10]:
df.isna().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [12]:
import pandas as pd

x =[1,2,3,4,5,6,7]
i = ['a','b','c','d','e','f','g']

a = pd.Series(x,index=i)
print(a)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [13]:
import pandas as pd

x= [1,2,3,4,5,6,7]
i = ('a','b','c','d','e','f','i')
s = pd.Series(x,index=i)
print(s)

a    1
b    2
c    3
d    4
e    5
f    6
i    7
dtype: int64

# What is Series?

a pandas series is like a column in a table.
Its a one-dimensional array holding data of any type.

In [14]:
import pandas as pd

a=[1,2,3,4]
myvar=pd.Series(a)
print(myvar)

0    1
1    2
2    3
3    4
dtype: int64

# Labels


if nothing else is specified, the values are labeled with their index number.First value has index 0, second value has index 1 etc.

this label can be used to access a specified value.

In [15]:
import pandas as pd

a=[10,20,30,40,50]

myseries=pd.Series(a)
print(myseries)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [16]:
# Create Labels


# with the index argument you can name your own labels.


a=[1,7,2]

myvar=pd.Series(a,index=["x","y","z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

In [17]:
# Key/Value object as series

# you can also use key value object like a dictionary when creating a series.

calories={"day1":420,"day2":340,"day3":230}

df=pd.Series(calories,index=["day1","day2"])
print(df)

day1    420
day2    340
dtype: int64

# DataFrames


Data sets in pandas are usually multi-dimensional tables called DataFrames.

Series is like a column a Dataframe is the whole table.

A pandas DataFrame is a 2 dimensional data structure like a 2 dimensional array, or table with rows and columns.

In [29]:
import pandas as pd

df = pd.read_csv('Employee.csv')

# df.head()
df.info()

# df.describe()

# df.isna().sum #return non-null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     50 non-null     int64
 1   FIRST_NAME      50 non-null     object
 2   LAST_NAME       50 non-null     object
 3   EMAIL           50 non-null     object
 4   PHONE_NUMBER    50 non-null     object
 5   HIRE_DATE       50 non-null     object
 6   JOB_ID          50 non-null     object
 7   SALARY          50 non-null     int64
 8   COMMISSION_PCT  50 non-null     object
 9   MANAGER_ID      50 non-null     object
 10  DEPARTMENT_ID   50 non-null     int64
dtypes: int64(3), object(8)
memory usage: 4.4+ KB

In [30]:
import pandas as pd

data ={
    'name':['Kuldip','sumit','ankit'],
    'age':[12,23,21]
}

df = pd.DataFrame(data)

df['marks']=[23,45,50]
df

     name  age  marks
0  Kuldip   12     23
1   sumit   23     45
2   ankit   21     50

In [47]:
import pandas as pd

data = {
    'name':['kuldip','sumit','ankit'],
    'age':[12,23,24]
}

df =pd.DataFrame(data)

df['marks'] = [23,None,56]

df.dropna(axis=1)

     name  age
0  kuldip   12
1   sumit   23
2   ankit   24

In [48]:
import pandas as pd

data = {
    'name':['kuldip','sumit','ankit'],
    'age':[21,22,34]
}

df = pd.DataFrame(data)

data

{'name': ['kuldip', 'sumit', 'ankit'], 'age': [21, 22, 34]}

In [49]:
df

     name  age
0  kuldip   21
1   sumit   22
2   ankit   34

In [50]:
df = pd.read_csv('iris.csv')

df.head()

df.isna().sum()

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [51]:
df = pd.read_csv('iris.csv')

df.head()

df.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [52]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [53]:
df.shape

(150, 5)

In [54]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [55]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [1]:
df = df.drop(columns=['sepal.width'],axis=1)

NameError: name 'df' is not defined

In [61]:
df =df.drop(columns=['species'],axis=1)

df

KeyError: "['species'] not found in axis"

In [63]:
import pandas as pd

df ={'names':['sumit','kuldip','shahil'],
     'age':[None,34,53],
     'marks':[45,None,55]
     }

data= pd.DataFrame(df)

data

    names   age  marks
0   sumit   NaN   45.0
1  kuldip  34.0    NaN
2  shahil  53.0   55.0

In [64]:
# data['marks'] = data['marks'].fillna(50)

data=data.dropna(axis=1)

data

    names
0   sumit
1  kuldip
2  shahil

In [67]:
df = pd.read_csv('iris.csv')

df.isna().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [68]:
import pandas as pd

data={
    "calories":[420,320,120],
    "duration":[40,20,45]
}

myvar=pd.DataFrame(data)
myvar

# Locate Row

# pandas use the loc attribute to return one or more specified rows.

# refers to the row index\
# print(myvar.loc[2])
print(myvar.loc[[0,1]])

   calories  duration
0       420        40
1       320        20

In [73]:
import pandas as pd 

df=pd.read_csv("iris.csv")
# df.head()
print(df.describe())
df.info()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [75]:
# Read Csv Files

import pandas as pd

df=pd.read_csv("Employee.csv")
print(df)
# print(df.to_string()) #to_string method will print entire dataset


# max_rows

# the number of rows returned is defined in pandas option settings.
# you can check your systems maximum rows with the pd.options.display.max_rows statement.

# print(pd.options.display.max_rows)

# pd.options.display.max_rows=9999
# df=pd.read_csv("data.csv")
# print(df)

    EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0           198       Donald     OConnell  DOCONNEL  650.507.9833  21-JUN-07
1           199      Douglas        Grant    DGRANT  650.507.9844  13-JAN-08
2           200     Jennifer       Whalen   JWHALEN  515.123.4444  17-SEP-03
3           201      Michael    Hartstein  MHARTSTE  515.123.5555  17-FEB-04
4           202          Pat          Fay      PFAY  603.123.6666  17-AUG-05
5           203        Susan       Mavris   SMAVRIS  515.123.7777  07-JUN-02
6           204      Hermann         Baer     HBAER  515.123.8888  07-JUN-02
7           205      Shelley      Higgins  SHIGGINS  515.123.8080  07-JUN-02
8           206      William        Gietz    WGIETZ  515.123.8181  07-JUN-02
9           100       Steven         King     SKING  515.123.4567  17-JUN-03
10          101        Neena      Kochhar  NKOCHHAR  515.123.4568  21-SEP-05
11          102          Lex      De Haan   LDEHAAN  515.123.4569  13-JAN-01
12          103    Alexander       Hunold   AHUNOLD  590.423.4567  03-JAN-06
13          104        Bruce        Ernst    BERNST  590.423.4568  21-MAY-07
14          105        David       Austin   DAUSTIN  590.423.4569  25-JUN-05
15          106        Valli    Pataballa  VPATABAL  590.423.4560  05-FEB-06
16          107        Diana      Lorentz  DLORENTZ  590.423.5567  07-FEB-07
17          108        Nancy    Greenberg  NGREENBE  515.124.4569  17-AUG-02
18          109       Daniel       Faviet   DFAVIET  515.124.4169  16-AUG-02
19          110         John         Chen     JCHEN  515.124.4269  28-SEP-05
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  30-SEP-05
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  07-MAR-06
22          113         Luis         Popp     LPOPP  515.124.4567  07-DEC-07
23          114          Den     Raphaely  DRAPHEAL  515.127.4561  07-DEC-02
24          115    Alexander         Khoo     AKHOO  515.127.4562  18-MAY-03
25          116       Shelli        Baida    SBAIDA  515.127.4563  24-DEC-05
26          117        Sigal       Tobias   STOBIAS  515.127.4564  24-JUL-05
27          118          Guy       Himuro   GHIMURO  515.127.4565  15-NOV-06
28          119        Karen   Colmenares  KCOLMENA  515.127.4566  10-AUG-07
29          120      Matthew        Weiss    MWEISS  650.123.1234  18-JUL-04
30          121         Adam        Fripp    AFRIPP  650.123.2234  10-APR-05
31          122        Payam     Kaufling  PKAUFLIN  650.123.3234  01-MAY-03
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234  10-OCT-05
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234  16-NOV-07
34          125        Julia        Nayer    JNAYER  650.124.1214  16-JUL-05
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224  28-SEP-06
36          127        James       Landry   JLANDRY  650.124.1334  14-JAN-07
37          128       Steven       Markle   SMARKLE  650.124.1434  08-MAR-08
38          129        Laura       Bissot   LBISSOT  650.124.5234  20-AUG-05
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234  30-OCT-05
40          131        James       Marlow   JAMRLOW  650.124.7234  16-FEB-05
41          132           TJ        Olson   TJOLSON  650.124.8234  10-APR-07
42          133        Jason       Mallin   JMALLIN  650.127.1934  14-JUN-04
43          134      Michael       Rogers   MROGERS  650.127.1834  26-AUG-06
44          135           Ki          Gee      KGEE  650.127.1734  12-DEC-07
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634  06-FEB-08
46          137       Renske       Ladwig   RLADWIG  650.121.1234  14-JUL-03
47          138      Stephen       Stiles   SSTILES  650.121.2034  26-OCT-05
48          139         John          Seo      JSEO  650.121.2019  12-FEB-06
49          140       Joshua        Patel    JPATEL  650.121.1834  06-APR-06

        JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID
0     SH_CLERK    2600             -         124             50
1     SH_CLERK    2600             -         124             50
2      AD_ASST    4400             -         101             10
3       MK_MAN   13000             -         100             20
4       MK_REP    6000             -         201             20
5       HR_REP    6500             -         101             40
6       PR_REP   10000             -         101             70
7       AC_MGR   12008             -         101            110
8   AC_ACCOUNT    8300             -         205            110
9      AD_PRES   24000             -          -              90
10       AD_VP   17000             -         100             90
11       AD_VP   17000             -         100             90
12     IT_PROG    9000             -         102             60
13     IT_PROG    6000             -         103             60
14     IT_PROG    4800             -         103             60
15     IT_PROG    4800             -         103             60
16     IT_PROG    4200             -         103             60
17      FI_MGR   12008             -         101            100
18  FI_ACCOUNT    9000             -         108            100
19  FI_ACCOUNT    8200             -         108            100
20  FI_ACCOUNT    7700             -         108            100
21  FI_ACCOUNT    7800             -         108            100
22  FI_ACCOUNT    6900             -         108            100
23      PU_MAN   11000             -         100             30
24    PU_CLERK    3100             -         114             30
25    PU_CLERK    2900             -         114             30
26    PU_CLERK    2800             -         114             30
27    PU_CLERK    2600             -         114             30
28    PU_CLERK    2500             -         114             30
29      ST_MAN    8000             -         100             50
30      ST_MAN    8200             -         100             50
31      ST_MAN    7900             -         100             50
32      ST_MAN    6500             -         100             50
33      ST_MAN    5800             -         100             50
34    ST_CLERK    3200             -         120             50
35    ST_CLERK    2700             -         120             50
36    ST_CLERK    2400             -         120             50
37    ST_CLERK    2200             -         120             50
38    ST_CLERK    3300             -         121             50
39    ST_CLERK    2800             -         121             50
40    ST_CLERK    2500             -         121             50
41    ST_CLERK    2100             -         121             50
42    ST_CLERK    3300             -         122             50
43    ST_CLERK    2900             -         122             50
44    ST_CLERK    2400             -         122             50
45    ST_CLERK    2200             -         122             50
46    ST_CLERK    3600             -         123             50
47    ST_CLERK    3200             -         123             50
48    ST_CLERK    2700             -         123             50
49    ST_CLERK    2500             -         123             50

# Viewing the data


One of the most used method for getting a quick overview of the DataFrame is the head() method.

the head() method returns the headers and a specific number of rows,starting from the top.

In [77]:
import pandas as pd

df=pd.read_csv("iris.csv")
print(df.head())
print(df.tail())

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

# Info about the data

the DataFrame object has a method called info() that gives you more info about the data set.

In [83]:
print(df.info())
print(df.shape)#rows columns
print(df.describe())
print(df.tail())
print(df.dtypes) #data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
(150, 5)
       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica
sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

----------------------------------------------------------------------------------------------------------


Practice Questions:-


Q-1: Create a pandas series from a python list[10,20,30,40].

->Print the series.

->Print only the first 2 elements using head().


Q-2: Create a Dataframe for student marks: Name:["Amit","Riya","Sumit","Pooja"], Math:[78,89,67,90],Science:[88,78,95,80].

->Print first 3 Rows.

->Show column names and data types.


Q-3: Read a CSV file named employee.csv into a DataFrame.

->Print first 5 rows.

->Print last 2 rows.

->Show number of rows and columns using shape.


Q-4:From the employees.csv show:

->Only column names.

->Summary statistics(mean,std,min,max etc) using describe()

In [84]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\vidhu\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: numpy>=1.18.5 in c:\users\vidhu\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vidhu\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vidhu\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\vidhu\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [91]:
# Q-1: Create a pandas series from a python list[10,20,30,40].
# ->Print the series.
# ->Print only the first 2 elements using head().

import pandas as pd

data = [10,20,30,40]
series = pd.Series(data)

print("Full series:")
print(series)

print("\nFirst 2 elements:")
print(series.head(2))

Full series:
0    10
1    20
2    30
3    40
dtype: int64

First 2 elements:
0    10
1    20
dtype: int64

In [103]:
# Q-2: Create a Dataframe for student marks: Name:["Amit","Riya","Sumit","Pooja"], Math:[78,89,67,90],Science:[88,78,95,80].
# ->Print first 3 Rows.
# ->Show column names and data types.

data = {
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Math":[78,89,67,90],
    "Science":[88,78,95,80]
}

df = pd.DataFrame(data)

print("First 3 Rows:")
print(df.head(3))

print("\nColums Name:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

First 3 Rows:
    Name  Math  Science
0   Amit    78       88
1   Riya    89       78
2  Sumit    67       95

Colums Name:
Index(['Name', 'Math', 'Science'], dtype='object')

Data Types:
Name       object
Math        int64
Science     int64
dtype: object

In [113]:
# Q-3: Read a CSV file named employee.csv into a DataFrame.
# ->Print first 5 rows.
# ->Print last 2 rows.
# ->Show number of rows and columns using shape.

import pandas as pd

df = pd.read_csv("employee.csv") 
print(df)


print("\nFisrt 5 rows:")
print(df.head(5))

print("\nLast 2 rows:")
print(df.tail(2))

print("Number of rows and columns:")
print(df.shape)

    EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0           198       Donald     OConnell  DOCONNEL  650.507.9833  21-JUN-07
1           199      Douglas        Grant    DGRANT  650.507.9844  13-JAN-08
2           200     Jennifer       Whalen   JWHALEN  515.123.4444  17-SEP-03
3           201      Michael    Hartstein  MHARTSTE  515.123.5555  17-FEB-04
4           202          Pat          Fay      PFAY  603.123.6666  17-AUG-05
5           203        Susan       Mavris   SMAVRIS  515.123.7777  07-JUN-02
6           204      Hermann         Baer     HBAER  515.123.8888  07-JUN-02
7           205      Shelley      Higgins  SHIGGINS  515.123.8080  07-JUN-02
8           206      William        Gietz    WGIETZ  515.123.8181  07-JUN-02
9           100       Steven         King     SKING  515.123.4567  17-JUN-03
10          101        Neena      Kochhar  NKOCHHAR  515.123.4568  21-SEP-05
11          102          Lex      De Haan   LDEHAAN  515.123.4569  13-JAN-01
12          103    Alexander       Hunold   AHUNOLD  590.423.4567  03-JAN-06
13          104        Bruce        Ernst    BERNST  590.423.4568  21-MAY-07
14          105        David       Austin   DAUSTIN  590.423.4569  25-JUN-05
15          106        Valli    Pataballa  VPATABAL  590.423.4560  05-FEB-06
16          107        Diana      Lorentz  DLORENTZ  590.423.5567  07-FEB-07
17          108        Nancy    Greenberg  NGREENBE  515.124.4569  17-AUG-02
18          109       Daniel       Faviet   DFAVIET  515.124.4169  16-AUG-02
19          110         John         Chen     JCHEN  515.124.4269  28-SEP-05
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  30-SEP-05
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  07-MAR-06
22          113         Luis         Popp     LPOPP  515.124.4567  07-DEC-07
23          114          Den     Raphaely  DRAPHEAL  515.127.4561  07-DEC-02
24          115    Alexander         Khoo     AKHOO  515.127.4562  18-MAY-03
25          116       Shelli        Baida    SBAIDA  515.127.4563  24-DEC-05
26          117        Sigal       Tobias   STOBIAS  515.127.4564  24-JUL-05
27          118          Guy       Himuro   GHIMURO  515.127.4565  15-NOV-06
28          119        Karen   Colmenares  KCOLMENA  515.127.4566  10-AUG-07
29          120      Matthew        Weiss    MWEISS  650.123.1234  18-JUL-04
30          121         Adam        Fripp    AFRIPP  650.123.2234  10-APR-05
31          122        Payam     Kaufling  PKAUFLIN  650.123.3234  01-MAY-03
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234  10-OCT-05
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234  16-NOV-07
34          125        Julia        Nayer    JNAYER  650.124.1214  16-JUL-05
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224  28-SEP-06
36          127        James       Landry   JLANDRY  650.124.1334  14-JAN-07
37          128       Steven       Markle   SMARKLE  650.124.1434  08-MAR-08
38          129        Laura       Bissot   LBISSOT  650.124.5234  20-AUG-05
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234  30-OCT-05
40          131        James       Marlow   JAMRLOW  650.124.7234  16-FEB-05
41          132           TJ        Olson   TJOLSON  650.124.8234  10-APR-07
42          133        Jason       Mallin   JMALLIN  650.127.1934  14-JUN-04
43          134      Michael       Rogers   MROGERS  650.127.1834  26-AUG-06
44          135           Ki          Gee      KGEE  650.127.1734  12-DEC-07
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634  06-FEB-08
46          137       Renske       Ladwig   RLADWIG  650.121.1234  14-JUL-03
47          138      Stephen       Stiles   SSTILES  650.121.2034  26-OCT-05
48          139         John          Seo      JSEO  650.121.2019  12-FEB-06
49          140       Joshua        Patel    JPATEL  650.121.1834  06-APR-06

        JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID
0     SH_CLERK    2600             -         124             50
1     SH_CLERK    2600             -         124             50
2      AD_ASST    4400             -         101             10
3       MK_MAN   13000             -         100             20
4       MK_REP    6000             -         201             20
5       HR_REP    6500             -         101             40
6       PR_REP   10000             -         101             70
7       AC_MGR   12008             -         101            110
8   AC_ACCOUNT    8300             -         205            110
9      AD_PRES   24000             -          -              90
10       AD_VP   17000             -         100             90
11       AD_VP   17000             -         100             90
12     IT_PROG    9000             -         102             60
13     IT_PROG    6000             -         103             60
14     IT_PROG    4800             -         103             60
15     IT_PROG    4800             -         103             60
16     IT_PROG    4200             -         103             60
17      FI_MGR   12008             -         101            100
18  FI_ACCOUNT    9000             -         108            100
19  FI_ACCOUNT    8200             -         108            100
20  FI_ACCOUNT    7700             -         108            100
21  FI_ACCOUNT    7800             -         108            100
22  FI_ACCOUNT    6900             -         108            100
23      PU_MAN   11000             -         100             30
24    PU_CLERK    3100             -         114             30
25    PU_CLERK    2900             -         114             30
26    PU_CLERK    2800             -         114             30
27    PU_CLERK    2600             -         114             30
28    PU_CLERK    2500             -         114             30
29      ST_MAN    8000             -         100             50
30      ST_MAN    8200             -         100             50
31      ST_MAN    7900             -         100             50
32      ST_MAN    6500             -         100             50
33      ST_MAN    5800             -         100             50
34    ST_CLERK    3200             -         120             50
35    ST_CLERK    2700             -         120             50
36    ST_CLERK    2400             -         120             50
37    ST_CLERK    2200             -         120             50
38    ST_CLERK    3300             -         121             50
39    ST_CLERK    2800             -         121             50
40    ST_CLERK    2500             -         121             50
41    ST_CLERK    2100             -         121             50
42    ST_CLERK    3300             -         122             50
43    ST_CLERK    2900             -         122             50
44    ST_CLERK    2400             -         122             50
45    ST_CLERK    2200             -         122             50
46    ST_CLERK    3600             -         123             50
47    ST_CLERK    3200             -         123             50
48    ST_CLERK    2700             -         123             50
49    ST_CLERK    2500             -         123             50

Fisrt 5 rows:
   EMPLOYEE_ID FIRST_NAME  LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          198     Donald   OConnell  DOCONNEL  650.507.9833  21-JUN-07
1          199    Douglas      Grant    DGRANT  650.507.9844  13-JAN-08
2          200   Jennifer     Whalen   JWHALEN  515.123.4444  17-SEP-03
3          201    Michael  Hartstein  MHARTSTE  515.123.5555  17-FEB-04
4          202        Pat        Fay      PFAY  603.123.6666  17-AUG-05

     JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID
0  SH_CLERK    2600             -         124             50
1  SH_CLERK    2600             -         124             50
2   AD_ASST    4400             -         101             10
3    MK_MAN   13000             -         100             20
4    MK_REP    6000             -         201             20

Last 2 rows:
    EMPLOYEE_ID FIRST_NAME LAST_NAME   EMAIL  PHONE_NUMBER  HIRE_DATE  \
48          139       John       Seo    JSEO  650.121.2019  12-FEB-06
49          140     Joshua     Patel  JPATEL  650.121.1834  06-APR-06

      JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID
48  ST_CLERK    2700             -         123             50
49  ST_CLERK    2500             -         123             50
Number of rows and columns:
(50, 11)

In [122]:
# Q-4:From the employees.csv show:
# ->Only column names.
# ->Summary statistics(mean,std,min,max etc) using describe()

import pandas as pd

df = pd.read_csv("employee.csv")

print("\nColumn names:")
print(df.columns)

print("\nSummary statistics(mean,std,min,max):")

print(df.describe())

Column names:
Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

Summary statistics(mean,std,min,max):
       EMPLOYEE_ID        SALARY  DEPARTMENT_ID
count    50.000000     50.000000       50.00000
mean    134.760000   6182.320000       57.60000
std      33.631594   4586.181772       25.11687
min     100.000000   2100.000000       10.00000
25%     112.250000   2725.000000       50.00000
50%     124.500000   4600.000000       50.00000
75%     136.750000   8150.000000       60.00000
max     206.000000  24000.000000      110.00000