# 2.Pandas Data Selection

In [1]:
import pandas as pd

data={
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Math":[78,89,56,90],
    "Physics":[88,78,95,80],
    "Science":[70,45,90,78]
}

df=pd.DataFrame(data)
df['mark']=[34,67,89,90]

df

    Name  Math  Physics  Science  mark
0   Amit    78       88       70    34
1   Riya    89       78       45    67
2  Sumit    56       95       90    89
3  Pooja    90       80       78    90

In [3]:
print(df[['Name','mark']])

    Name  mark
0   Amit    34
1   Riya    67
2  Sumit    89
3  Pooja    90

In [2]:
# 1.Selecting Columns

# single column

import pandas as pd

data={
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Math":[78,89,56,90],
    "Physics":[88,78,95,80],
    "Science":[70,45,90,78]
}

df=pd.DataFrame(data)

print(df[["Math",'Science','Physics']])

# print(df["Name"])
# multiple columns

# print(df[["Math","Physics"]])

   Math  Science  Physics
0    78       70       88
1    89       45       78
2    56       90       95
3    90       78       80

In [8]:
# 2. Selecting Rows

# using iloc by index number

data={
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Math":[78,89,56,90],
    "Physics":[88,78,95,80],
    "Science":[70,45,90,78]
}

df=pd.DataFrame(data)
# print(df[df["Math"]>80])
# print(df[(df["Math"]>70) & (df["Physics"]>80)])
# print(df)
# print(df.iloc[2])
print(df.iloc[0:3]) 


# using loc by label/index name

# print(df.loc[])
# print(df.loc[0:2])

    Name  Math  Physics  Science
0   Amit    78       88       70
1   Riya    89       78       45
2  Sumit    56       95       90

In [12]:
# 3. Conditional Selection(boolean indexing)

# ex:Student with Math>70

# print(df[df["Math"]>70])



# 4.Multiple Conditions

# ex:Math>70 and science>80

# print(df[(df["Math"]>70) & (df["Physics"]>80)])
# print(df[(df["Math"]>70) | (df['Physics']>80)])


# 5.Selecting specific rows + columns

# ex:Name and Science column of first 2 students

print(df.loc[0:1,["Name","Science"]])

   Name  Science
0  Amit       70
1  Riya       45

----------------------------------------------------------------------------------------------------------






Pandas Data Selection-Practice Questions:-


Dataset={
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Math":[78,89,7,90],
    "Science":[88,76,95,80]
}


Q-1: Use Above Dataset and solve this problems.

 (i) Select Only Math column.

(ii) Select only the Name and Science columns.

(iii) Select the first 2 rows using iloc.

(iv) Select rows with index 1 and 2.

(v) Get all students who scored more than 70 in Math.

(vi) Get students with Math>70 and Science>80.

(vii) Get students with Math>85 or Science>90.

(viii) Select Name and Science of the first 2 Students.



Q-2: Suppose you have a file employee.csv.

(1) Select only Name and Salary.

(2) Select Employees with Salary>80000.

(3) Select employees who work in HR department.



Q-3: data = {
    "Player": ["Virat", "Rohit", "Dhoni", "Sachin", "Hardik"],
    "Runs": [78, 102, 45, 120, 65],
    "Wickets": [0, 1, 2, 0, 3],
    "Team": ["India", "India", "India", "India", "India"]
}

1. Select only the Runs column.

2. Select Player and Runs columns.

3. Select first 3 rows using iloc.

4. Select last 2 players using loc.

5. Show players who scored more than 70 runs.

6. Show players who scored more than 50 runs and took at least 1 wicket.


Q-4: data = {
    "FlightNo": [101, 102, 103, 104, 105],
    "Airline": ["IndiGo", "Air India", "SpiceJet", "GoAir", "Vistara"],
    "Price": [4500, 5200, 3900, 6100, 7000],
    "Duration": [2.5, 3.0, 2.0, 2.8, 3.5]
}

1. Select the Airline column.

2. Select rows of flights 101 and 104 only.

3. Show flights with price greater than 5000.

4. Show flights with duration less than 3 hours and price under 6000.


Q-5: data = {
    "Product": ["Laptop", "Mobile", "Shoes", "Watch", "Headphones"],
    "Price": [60000, 20000, 4000, 7000, 2000],
    "Stock": [12, 30, 50, 20, 100]
}

1. Select the Price column.

2. Select Product and Stock columns.

3. Show products costing more than 10,000.

4. Show products with price < 10,000 and stock > 20.


Q-6 data = {
    "Name": ["Aman", "Priya", "Sumit", "Neha", "Ravi"],
    "Math": [88, 45, 72, 95, 60],
    "Science": [76, 80, 65, 90, 70],
    "English": [60, 75, 70, 85, 55]
}

1. Select the first 2 rows.

2. Select Name and English columns.

3. Show students who scored more than 70 in Math.

4. Show students who scored more than 60 in all three subjects.


----------------------------------------------------------------------------------------------------------

# Pandas Data Selection-Practice Question's Answer:-

In [5]:
import pandas as pd

Dataset={ 
            "Name":["Amit","Riya","Sumit","Pooja"],
            "Math":[78,89,7,90], 
            "Science":[88,76,95,80] 
        }

df = pd.DataFrame(Dataset)

print(df)

    Name  Math  Science
0   Amit    78       88
1   Riya    89       76
2  Sumit     7       95
3  Pooja    90       80

# Q-1: Use Above Dataset and solve this problems.

In [25]:
# (i) Select Only Math column.

print(df["Math"])

0    78
1    89
2     7
3    90
Name: Math, dtype: int64

In [8]:
# (ii) Select only the Name and Science columns.

print(df[['Name','Science']])

    Name  Science
0   Amit       88
1   Riya       76
2  Sumit       95
3  Pooja       80

In [9]:
# (iii) Select the first 2 rows using iloc.

df.iloc[2]

Name       Sumit
Math           7
Science       95
Name: 2, dtype: object

In [13]:
# (iv) Select rows with index 1 and 2.

df.iloc[[1,2]]

    Name  Math  Science
1   Riya    89       76
2  Sumit     7       95

In [39]:
# (v) Get all students who scored more than 70 in Math.

df[df["Math"]>70]

    Name  Math  Science
0   Amit    78       88
1   Riya    89       76
3  Pooja    90       80

In [23]:
# (vi) Get students with Math>70 and Science>80.

print(df[(df["Math"]>70) & (df["Science"]>80)])

   Name  Math  Science
0  Amit    78       88

In [24]:
# (vii) Get students with Math>85 or Science>90.

print(df[(df["Math"]>85) | (df["Science"]>90)])

    Name  Math  Science
1   Riya    89       76
2  Sumit     7       95
3  Pooja    90       80

In [32]:
# (viii) Select Name and Science of the first 2 Students.

df.loc[[0,1], ["Name","Science"]]

   Name  Science
0  Amit       88
1  Riya       76

# Q-2: Suppose you have a file employees.csv.

In [23]:
# (1) Select only Name and Salary.
import pandas as pd

df = pd.read_csv("employees.csv")
# print(df)

print(df[["First Name","Salary"]])

    First Name  Salary
0      Douglas   97308
1       Thomas   61933
2        Maria  130590
3        Jerry  138705
4        Larry  101004
..         ...     ...
995      Henry  132483
996    Phillip   42392
997    Russell   96914
998      Larry   60500
999     Albert  129949

[1000 rows x 2 columns]

In [25]:
# (2) Select Employees with Salary>80000.

print(df[df["Salary"]>80000])

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
5       Dennis    Male   4/18/1987         1:35 AM  115163   10.125
..         ...     ...         ...             ...     ...      ...
992    Anthony    Male  10/16/2011         8:35 AM  112769   11.625
994     George    Male   6/21/2013         5:47 PM   98874    4.479
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management             Team
0                True        Marketing
2               False          Finance
3                True          Finance
4                True  Client Services
5               False            Legal
..                ...              ...
992              True          Finance
994              True        Marketing
995             False     Distribution
997             False          Product
999              True            Sales

[598 rows x 8 columns]

In [32]:
# (3) Select employees who work in HR department.

print(df)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]

# Q-3:

In [34]:
data = { 
        "Player": ["Virat", "Rohit", "Dhoni", "Sachin", "Hardik"], 
        "Runs": [78, 102, 45, 120, 65], 
        "Wickets": [0, 1, 2, 0, 3], 
        "Team": ["India", "India", "India", "India", "India"] 
        }
df = pd.DataFrame(data)

# print(df)
# Select only the Runs column.

print(df["Runs"])

0     78
1    102
2     45
3    120
4     65
Name: Runs, dtype: int64

In [9]:
# (1) Select Player and Runs columns.

print(df[["Player","Runs"]])

   Player  Runs
0   Virat    78
1   Rohit   102
2   Dhoni    45
3  Sachin   120
4  Hardik    65

In [12]:
# (2) Select first 3 rows using iloc.

print(df.iloc[0:3])

df

  Player  Runs  Wickets   Team
0  Virat    78        0  India
1  Rohit   102        1  India
2  Dhoni    45        2  India

   Player  Runs  Wickets   Team
0   Virat    78        0  India
1   Rohit   102        1  India
2   Dhoni    45        2  India
3  Sachin   120        0  India
4  Hardik    65        3  India

In [17]:
# (3) Select last 2 players using loc.

print(df.loc[3:4])

   Player  Runs  Wickets   Team
3  Sachin   120        0  India
4  Hardik    65        3  India

In [19]:
# (4) Show players who scored more than 70 runs.

print(df[df["Runs"]>70])

   Player  Runs  Wickets   Team
0   Virat    78        0  India
1   Rohit   102        1  India
3  Sachin   120        0  India

In [42]:
# (5) Show players who scored more than 50 runs and took at least 1 wicket.

print(df)

df[(df["Runs"]>50) & (df["Wickets"]>=1)]

   Player  Runs  Wickets   Team
0   Virat    78        0  India
1   Rohit   102        1  India
2   Dhoni    45        2  India
3  Sachin   120        0  India
4  Hardik    65        3  India

   Player  Runs  Wickets   Team
1   Rohit   102        1  India
4  Hardik    65        3  India

# Q-4:

In [49]:
data = { 
        "FlightNo": [101, 102, 103, 104, 105], 
        "Airline": ["IndiGo", "Air India", "SpiceJet", "GoAir", "Vistara"], 
        "Price": [4500, 5200, 3900, 6100, 7000], 
        "Duration": [2.5, 3.0, 2.0, 2.8, 3.5] 
        }

df = pd.DataFrame(data)
print(df)

# 1. Select the Airline column.
print("-----------")
print(df["Airline"])

   FlightNo    Airline  Price  Duration
0       101     IndiGo   4500       2.5
1       102  Air India   5200       3.0
2       103   SpiceJet   3900       2.0
3       104      GoAir   6100       2.8
4       105    Vistara   7000       3.5
-----------
0       IndiGo
1    Air India
2     SpiceJet
3        GoAir
4      Vistara
Name: Airline, dtype: object

In [52]:
# 2. Select rows of flights 101 and 104 only.

print(df[(df["FlightNo"]==101) | (df["FlightNo"]==104)])

   FlightNo Airline  Price  Duration
0       101  IndiGo   4500       2.5
3       104   GoAir   6100       2.8

In [54]:
# 3. Show flights with price greater than 5000.

df[df["Price"]>5000]

   FlightNo    Airline  Price  Duration
1       102  Air India   5200       3.0
3       104      GoAir   6100       2.8
4       105    Vistara   7000       3.5

In [59]:
# 4. Show flights with duration less than 3 hours and price under 6000.

df1 = df[(df["Duration"]<3)  &  (df["Price"]<6000)]

print(df1)


print("----------")
df2 = df.loc[(df["Duration"]<3)  &  (df["Price"]<6000)]

print(df2)

   FlightNo   Airline  Price  Duration
0       101    IndiGo   4500       2.5
2       103  SpiceJet   3900       2.0
----------
   FlightNo   Airline  Price  Duration
0       101    IndiGo   4500       2.5
2       103  SpiceJet   3900       2.0

# Q-5:

In [66]:
 data = { 
        "Product": ["Laptop", "Mobile", "Shoes", "Watch", "Headphones"], 
        "Price": [60000, 20000, 4000, 7000, 2000], 
        "Stock": [12, 30, 50, 20, 100] 
        }

df = pd.DataFrame(data)

print(df)
# 1. Select the Price column.

print("---------")
df["Price"]

      Product  Price  Stock
0      Laptop  60000     12
1      Mobile  20000     30
2       Shoes   4000     50
3       Watch   7000     20
4  Headphones   2000    100
---------

0    60000
1    20000
2     4000
3     7000
4     2000
Name: Price, dtype: int64

In [70]:
# 2. Select Product and Stock columns.

print(df[["Product","Stock"]])

      Product  Stock
0      Laptop     12
1      Mobile     30
2       Shoes     50
3       Watch     20
4  Headphones    100

In [73]:
# 3. Show products costing more than 10,000.

print(df[df["Price"] >10000])

  Product  Price  Stock
0  Laptop  60000     12
1  Mobile  20000     30

In [75]:
# 4. Show products with price < 10,000 and stock > 20.

df.loc[(df["Price"]<10000) & (df["Stock"]>20)]

      Product  Price  Stock
2       Shoes   4000     50
4  Headphones   2000    100

# Q-6

In [85]:
 data = { 
        "Name": ["Aman", "Priya", "Sumit", "Neha", "Ravi"], 
        "Math": [88, 45, 72, 95, 60], 
        "Science": [76, 80, 65, 90, 70], 
        "English": [60, 75, 70, 85, 55] 
        }

df = pd.DataFrame(data)

print(df)

# 1. Select the first 2 rows.

df.iloc[[0,1]]

    Name  Math  Science  English
0   Aman    88       76       60
1  Priya    45       80       75
2  Sumit    72       65       70
3   Neha    95       90       85
4   Ravi    60       70       55

    Name  Math  Science  English
0   Aman    88       76       60
1  Priya    45       80       75

In [88]:
# 2. Select Name and English columns.

df[["Name","English"]]

    Name  English
0   Aman       60
1  Priya       75
2  Sumit       70
3   Neha       85
4   Ravi       55

In [90]:
# 3. Show students who scored more than 70 in Math.

df[df["Math"]>70]

    Name  Math  Science  English
0   Aman    88       76       60
2  Sumit    72       65       70
3   Neha    95       90       85

In [101]:
# 4. Show students who scored more than 60 in all three subjects.

# df[(df["Math"]>60) & (df["Science"]>60) & (df["English"]>60)]


df[(df[["Math","Science","English"]]>60).all(axis=1)]

    Name  Math  Science  English
2  Sumit    72       65       70
3   Neha    95       90       85