# Data Cleaning:


Handling Missing values in pandas.

ex:survey me kux log apana age nai batate koi product price mising hota hai etc.

Pandas me missing data ko NAN(not a number) se represent kiya jata hai.

In [53]:
import pandas as pd


data={
    "Name":["Amit","Riya","Sumit","Pooja"],
    "Age":[25,None,30,22],
    "Salary":[50000,60000,None,55000]
}

df=pd.DataFrame(data)
df

    Name   Age   Salary
0   Amit  25.0  50000.0
1   Riya   NaN  60000.0
2  Sumit  30.0      NaN
3  Pooja  22.0  55000.0

In [8]:
df.isna().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [9]:
df['Age']= df['Age'].fillna(df['Age'].mean())
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000      NaN
3  Pooja  22.000000  55000.0

In [10]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [11]:
df =df.dropna(axis=1)

In [12]:
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [13]:
df.isna().sum()

Name      0
Age       0
Salary    0
dtype: int64

In [14]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [15]:
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [16]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [26]:
df.isna().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [27]:
df.dropna()

    Name   Age   Salary
0   Amit  25.0  50000.0
3  Pooja  22.0  55000.0

In [17]:

df = df.dropna()
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [19]:
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [20]:
df.dropna(axis=1)

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [25]:
df["Age"]=(df['Age'].fillna(df['Age'].mean()))

df["Salary"]=(df["Salary"].fillna(df["Salary"].median()))

print(df["Age"])
print(df["Salary"])

0    25.000000
1    25.666667
2    30.000000
3    22.000000
Name: Age, dtype: float64
0    50000.0
1    60000.0
2    55000.0
3    55000.0
Name: Salary, dtype: float64

In [24]:
df

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [29]:
# 1.Checking missing values-->isnull()

print(df.isnull())

print("-------------")
# Count missing values column wise

print(df.isnull().sum())

print("-------------")
# 2.Remove missing values-->dropna()

print(df.dropna())

print("-------------")
# Remove columns with missing values

print(df.dropna(axis=1))

print("-------------")
# 3.Fill missing values-->fillna()

# fill with fixed value
print(df.fillna(0))

# fill with columns mean/median
df['Age']=(df['Age'].fillna(df['Age'].mean()))


df

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
-------------
Name      0
Age       0
Salary    0
dtype: int64
-------------
    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0
-------------
    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0
-------------
    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

    Name        Age   Salary
0   Amit  25.000000  50000.0
1   Riya  25.666667  60000.0
2  Sumit  30.000000  55000.0
3  Pooja  22.000000  55000.0

In [33]:
# Forward fill: Upar vali row ka value niche copy hojata hai

import pandas as pd

data={
    "Name":["Amit","Riya","Sumit","Pooja","Raj"],
    "Math":[78,None,65,88,None],
    "Science":[85,88,None,90,75],
    "English":[80,None,72,85,70]
}

df=pd.DataFrame(data)

print("Original:\n",df)

print("-------------")
# forward fill

df_ffill=df.fillna(method="ffill")
print("\nAfter Forward Fill:\n",df_ffill)

df_ffill

Original:
     Name  Math  Science  English
0   Amit  78.0     85.0     80.0
1   Riya   NaN     88.0      NaN
2  Sumit  65.0      NaN     72.0
3  Pooja  88.0     90.0     85.0
4    Raj   NaN     75.0     70.0
-------------

After Forward Fill:
     Name  Math  Science  English
0   Amit  78.0     85.0     80.0
1   Riya  78.0     88.0     80.0
2  Sumit  65.0     88.0     72.0
3  Pooja  88.0     90.0     85.0
4    Raj  88.0     75.0     70.0

    Name  Math  Science  English
0   Amit  78.0     85.0     80.0
1   Riya  78.0     88.0     80.0
2  Sumit  65.0     88.0     72.0
3  Pooja  88.0     90.0     85.0
4    Raj  88.0     75.0     70.0

In [34]:
# Backward fill

# Neche wali row ka value upar copy ho jata hai.

df_bfill=df.fillna(method="bfill")
print("\nAfter Backward Fill:\n",df_bfill)

After Backward Fill:
     Name  Math  Science  English
0   Amit  78.0     85.0     80.0
1   Riya  65.0     88.0     72.0
2  Sumit  65.0     90.0     72.0
3  Pooja  88.0     90.0     85.0
4    Raj   NaN     75.0     70.0

In [35]:
# Conditional Fill

# Specific condtion ke hisab se fill krna.

# ex: Agar English marks missing hai to 70 daal do

df.loc[df['English'].isnull(),'English']=70
print("\nAfter Conditional Fill:\n",df)

After Conditional Fill:
     Name  Math  Science  English
0   Amit  78.0     85.0     80.0
1   Riya   NaN     88.0     70.0
2  Sumit  65.0      NaN     72.0
3  Pooja  88.0     90.0     85.0
4    Raj   NaN     75.0     70.0

In [36]:
# Column Specific missing values handling : har column ke liye alag-alg tarike se missing values bharna.

# 1.Ek column ke liye fillna

import pandas as pd

data={
    "Name":["Aman","Sumit","Ranu",None],
    "Age":[20,None,25,30],
    "Salary":[50000,60000,None,70000]
}

df=pd.DataFrame(data)

# sirf Age column ke NaN ko mean se fill karna

df['Age']=df["Age"].fillna(df['Age'].mean())

# sirf Salary column ke NaN ko 0 se fill krna

df['Salary']=df['Salary'].fillna(0)

print(df)

    Name   Age   Salary
0   Aman  20.0  50000.0
1  Sumit  25.0  60000.0
2   Ranu  25.0      0.0
3   None  30.0  70000.0

In [37]:
# 2. Alag alag colmns ke liye alag tarike se ek sath

# har column ke liye rule define karo 

fill_rules={
    "Age":df['Age'].median(),
    "Salary":0,
    "Name":"Unknown"
}

df=df.fillna(value=fill_rules)
print(df)

      Name   Age   Salary
0     Aman  20.0  50000.0
1    Sumit  25.0  60000.0
2     Ranu  25.0      0.0
3  Unknown  30.0  70000.0

In [38]:
# 3.Conditional filling (column specific)

# maan lo salary missing hai to usako age*2000 se bhrna hai

df['Salary']=df.apply(lambda row:row['Age']*2000 if pd.isna(row['Salary']) else row['Salary'],axis=1)
print(df)

      Name   Age   Salary
0     Aman  20.0  50000.0
1    Sumit  25.0  60000.0
2     Ranu  25.0      0.0
3  Unknown  30.0  70000.0

In [52]:
# 3.1 Fill based on another column

# we want to fill missing Age with default values based on City

import pandas as pd
import numpy as np

data={
    "Name":['Alice','Bob','Charlie','David'],
    "Age":[25,None,30,None],
    "City":['Delhi','Mumbai','Delhi','Mumbai']
}

df=pd.DataFrame(data)
print(df)

print("--------------")
df.loc[df['City']=='Delhi','Age']=df.loc[df['City']=='Delhi','Age'].fillna(28)
df.loc[df['City']=='Mumbai','Age']=df.loc[df['City']=='Mumbai','Age'].fillna(32)
print(df)


# 2.Using np.where:we can also use np.where for conditional filling.

df['Age']=np.where(df['Age'].isna()&(df['City']=='Delhi'),28,df['Age'])
df['Age']=np.where(df['Age'].isna()&(df['City']=='Mumbai'),32,df['Age'])
df

      Name   Age    City
0    Alice  25.0   Delhi
1      Bob   NaN  Mumbai
2  Charlie  30.0   Delhi
3    David   NaN  Mumbai
--------------
      Name   Age    City
0    Alice  25.0   Delhi
1      Bob  32.0  Mumbai
2  Charlie  30.0   Delhi
3    David  32.0  Mumbai

      Name   Age    City
0    Alice  25.0   Delhi
1      Bob  32.0  Mumbai
2  Charlie  30.0   Delhi
3    David  32.0  Mumbai

In [41]:
# 4. Diffrent fill for numeric vs categorical filling automatically

# Numeric columns fill with mean

for col in df.select_dtypes(include='number'):
    df[col]=df[col].fillna(df[col].mean())

# string columns->fill with "Unknown"

for col in df.select_dtypes(include='object'):
    df[col]=df[col].fillna("Unknown")
print(df)

      Name   Age   Salary
0     Aman  20.0  50000.0
1    Sumit  25.0  60000.0
2     Ranu  25.0      0.0
3  Unknown  30.0  70000.0

In [18]:
# interpolate():- ye missing values ko fill karne ka ek smart mathematical tarika hai

# c Basic Linear interpolation:-Missing values ko linearly guess krta hai(previous or next value ke beech average)


import pandas as pd

data={
    "Day":[1,2,3,4,5,6,7],
    "Temperature":[30,None,32,None,36,None,40],
}

df=pd.DataFrame(data)

print("Original:\n",df)

# Linear Interpolation

df["Temperature"]=df["Temperature"].interpolate()
print("\nAfter Linear Interpolation:\n",df)

Original:
    Day  Temperature
0    1         30.0
1    2          NaN
2    3         32.0
3    4          NaN
4    5         36.0
5    6          NaN
6    7         40.0

After Linear Interpolation:
    Day  Temperature
0    1         30.0
1    2         31.0
2    3         32.0
3    4         34.0
4    5         36.0
5    6         38.0
6    7         40.0

# Practice Questions:-

Q-1: Employee Dataset

data={
    "Employee":["Raj","Simran","Aman","Neha"],
    "Departent":["HR",None,"IT","Finance"],
    "Salary":[40000,50000,None,45000]
}

1. Find which values are missing.

2. Count how many missing values are in each column.

3. Remove rows with missing values.

4.Fill missing Department with "Unknown".

5. Fill missing Salary with average salary.



Q-2: Product Dataset

data={
    "Product":["Laptop","Mobile","Shoes","Watch"],
    "Price":[60000,None,4000,None],
    "Stock":[10,20,None,15]
}

1. Show missing values.

2.Drop columns with missing values.

3.Fill missing price with 0.

4. Fill missing Stock with median of Stock.



Q-3: Import students.csv file.

1. Find out how many missing values are there in each column.

2. Remove all rows where any value is missing.

3. Remove the column if it contains any missing values.

4. Fill all missing values with 0.

5. Fill missing values in Math with the mean of Math Column.

6. Use forward fill(ffill) to fill missing values.

7. Use Backward fill(bfill) to fill missing values.

8. Fill missing Science marks with the median of Science,but keep others unchanged.

9. If English is missing, fill it with 70.

10. Verify that no missing values remai\
n in the dataset after applying fill.



Q-4: Import employee.csv file.

1. Show True/False matrix where missing values are present.

2. Find the total number of missing values in each column.

3. Delete rows where Department is missing.

4. Replace missing salaries with the mean salary.

5. Replace missing experience with the median value of the column.

6. Replace missing department with the most frequent department(mode).

7. Diffrent Fill stretegy.

-> Fill Salary with mean.

-> Fill Experience with 0.

-> Fill Department with "Unknown".

8. Find how many rows have more than 1 missing value.

9. Custom Conditional fill

->If Salary is missing and Department ="IT", fill with 60000.

->If Salary is missing and Department="Finance",fill with 58000.

10. Interpolation

Try Using interpolate() to fill numeric missing values(Salary,Experience)

# Q-1: Employee Dataset

In [2]:
import pandas as pd

data={ 
        "Employee":["Raj","Simran","Aman","Neha"], 
        "Department":["HR",None,"IT","Finance"], 
        "Salary":[40000,50000,None,45000] 
    }

df = pd.DataFrame(data)

df

  Employee Department   Salary
0      Raj         HR  40000.0
1   Simran       None  50000.0
2     Aman         IT      NaN
3     Neha    Finance  45000.0

In [3]:
# # 1. Find which values are missing.

print(df.isna())

# print("-------------")
# # 2. Count how many missing values are in each column.

print(df.isna().sum())

# print("-------------")
# # 3. Remove rows with missing values.

print(df.dropna())

# print("-------------")
# # 4.Fill missing Department with "Unknown".

df["Department"] = df["Department"].fillna("Unknown")
df

# print("-------------")
# # 5. Fill missing Salary with average salary.

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

   Employee  Department  Salary
0     False       False   False
1     False        True   False
2     False       False    True
3     False       False   False
Employee      0
Department    1
Salary        1
dtype: int64
  Employee Department   Salary
0      Raj         HR  40000.0
3     Neha    Finance  45000.0

  Employee Department   Salary
0      Raj         HR  40000.0
1   Simran    Unknown  50000.0
2     Aman         IT  45000.0
3     Neha    Finance  45000.0

# Q-2: Product Dataset

In [39]:
import pandas as pd

data={ 
        "Product":["Laptop","Mobile","Shoes","Watch"], 
        "Price":[60000,None,4000,None], 
        "Stock":[10,20,None,15] 
    }

df = pd.DataFrame(data)

df

  Product    Price  Stock
0  Laptop  60000.0   10.0
1  Mobile      NaN   20.0
2   Shoes   4000.0    NaN
3   Watch      NaN   15.0

In [40]:
# 1. Show missing values.

print(df.isna().sum())

Product    0
Price      2
Stock      1
dtype: int64

In [41]:
# 2.Drop columns with missing values.

print(df.dropna(axis=1))

  Product
0  Laptop
1  Mobile
2   Shoes
3   Watch

In [42]:

# 3.Fill missing price with 0.

df["Price"] = df["Price"].fillna(0)
print(df)

  Product    Price  Stock
0  Laptop  60000.0   10.0
1  Mobile      0.0   20.0
2   Shoes   4000.0    NaN
3   Watch      0.0   15.0

In [43]:
# 4. Fill missing Stock with median of Stock.

df["Stock"] = df["Stock"].fillna(df["Stock"].median())
print(df)

  Product    Price  Stock
0  Laptop  60000.0   10.0
1  Mobile      0.0   20.0
2   Shoes   4000.0   15.0
3   Watch      0.0   15.0

# Q-3: Import students_marks.csv file.

In [2]:
import pandas as pd

df = pd.read_csv("students_marks.csv")
df

       Name  Class  Math  Science  English
0      Amit     10  78.0      NaN     88.0
1      Riya     10   NaN     81.0     76.0
2     Sumit     11  65.0     70.0      NaN
3     Pooja     11  88.0     89.0     90.0
4       Raj     12  55.0      NaN     65.0
5     Sneha     12  95.0     92.0     94.0
6    Rajesh      9  99.0     87.0     90.0
7     Mohit     11  67.0     91.0     56.0
8   Krishna     12  90.0     91.0     97.0
9    Mukesh     10  78.0     89.0     70.0
10  Radhika     11  89.0     78.0     87.0
11   Vishal     12  45.0     67.0     54.0
12   Nilesh     12  67.0     78.0     89.0
13  Prakash     10  50.0     45.0     33.0
14  Kalpesh     12  45.0     78.0     90.0
15   Adarsh     12  90.0     78.0     45.0
16     Raja     10  67.0     58.0     59.0
17  Pritesh      9  56.0     90.0     45.0
18   Mahesh     10  45.0     33.0     36.0
19  Poojesh      8  90.0     99.0     89.0
20    Akash      7  88.0     45.0     67.0

In [45]:
# 1. Find out how many missing values are there in each column.

df.isna().sum()

Name       0
Class      0
Math       1
Science    2
English    1
dtype: int64

In [46]:
# 2. Remove all rows where any value is missing.

df.dropna()

       Name  Class  Math  Science  English
3     Pooja     11  88.0     89.0     90.0
5     Sneha     12  95.0     92.0     94.0
6    Rajesh      9  99.0     87.0     90.0
7     Mohit     11  67.0     91.0     56.0
8   Krishna     12  90.0     91.0     97.0
9    Mukesh     10  78.0     89.0     70.0
10  Radhika     11  89.0     78.0     87.0
11   Vishal     12  45.0     67.0     54.0
12   Nilesh     12  67.0     78.0     89.0
13  Prakash     10  50.0     45.0     33.0
14  Kalpesh     12  45.0     78.0     90.0
15   Adarsh     12  90.0     78.0     45.0
16     Raja     10  67.0     58.0     59.0
17  Pritesh      9  56.0     90.0     45.0
18   Mahesh     10  45.0     33.0     36.0
19  Poojesh      8  90.0     99.0     89.0
20    Akash      7  88.0     45.0     67.0

In [47]:
# 3. Remove the column if it contains any missing values.

df.dropna(axis=1)

       Name  Class
0      Amit     10
1      Riya     10
2     Sumit     11
3     Pooja     11
4       Raj     12
5     Sneha     12
6    Rajesh      9
7     Mohit     11
8   Krishna     12
9    Mukesh     10
10  Radhika     11
11   Vishal     12
12   Nilesh     12
13  Prakash     10
14  Kalpesh     12
15   Adarsh     12
16     Raja     10
17  Pritesh      9
18   Mahesh     10
19  Poojesh      8
20    Akash      7

In [48]:
# 4. Fill all missing values with 0.

df.fillna(0)

       Name  Class  Math  Science  English
0      Amit     10  78.0      0.0     88.0
1      Riya     10   0.0     81.0     76.0
2     Sumit     11  65.0     70.0      0.0
3     Pooja     11  88.0     89.0     90.0
4       Raj     12  55.0      0.0     65.0
5     Sneha     12  95.0     92.0     94.0
6    Rajesh      9  99.0     87.0     90.0
7     Mohit     11  67.0     91.0     56.0
8   Krishna     12  90.0     91.0     97.0
9    Mukesh     10  78.0     89.0     70.0
10  Radhika     11  89.0     78.0     87.0
11   Vishal     12  45.0     67.0     54.0
12   Nilesh     12  67.0     78.0     89.0
13  Prakash     10  50.0     45.0     33.0
14  Kalpesh     12  45.0     78.0     90.0
15   Adarsh     12  90.0     78.0     45.0
16     Raja     10  67.0     58.0     59.0
17  Pritesh      9  56.0     90.0     45.0
18   Mahesh     10  45.0     33.0     36.0
19  Poojesh      8  90.0     99.0     89.0
20    Akash      7  88.0     45.0     67.0

In [51]:
# 5. Fill missing values in Math with the mean of Math Column.

df["Math"] = df["Math"].fillna(df["Math"].mean())
df

       Name  Class   Math  Science  English
0      Amit     10  78.00      NaN     88.0
1      Riya     10  72.35     81.0     76.0
2     Sumit     11  65.00     70.0      NaN
3     Pooja     11  88.00     89.0     90.0
4       Raj     12  55.00      NaN     65.0
5     Sneha     12  95.00     92.0     94.0
6    Rajesh      9  99.00     87.0     90.0
7     Mohit     11  67.00     91.0     56.0
8   Krishna     12  90.00     91.0     97.0
9    Mukesh     10  78.00     89.0     70.0
10  Radhika     11  89.00     78.0     87.0
11   Vishal     12  45.00     67.0     54.0
12   Nilesh     12  67.00     78.0     89.0
13  Prakash     10  50.00     45.0     33.0
14  Kalpesh     12  45.00     78.0     90.0
15   Adarsh     12  90.00     78.0     45.0
16     Raja     10  67.00     58.0     59.0
17  Pritesh      9  56.00     90.0     45.0
18   Mahesh     10  45.00     33.0     36.0
19  Poojesh      8  90.00     99.0     89.0
20    Akash      7  88.00     45.0     67.0

In [54]:
# 6. Use forward fill(ffill) to fill missing values.

df_ffill = df.fillna(method = 'ffill')
df_ffill

       Name  Class   Math  Science  English
0      Amit     10  78.00      NaN     88.0
1      Riya     10  72.35     81.0     76.0
2     Sumit     11  65.00     70.0     76.0
3     Pooja     11  88.00     89.0     90.0
4       Raj     12  55.00     89.0     65.0
5     Sneha     12  95.00     92.0     94.0
6    Rajesh      9  99.00     87.0     90.0
7     Mohit     11  67.00     91.0     56.0
8   Krishna     12  90.00     91.0     97.0
9    Mukesh     10  78.00     89.0     70.0
10  Radhika     11  89.00     78.0     87.0
11   Vishal     12  45.00     67.0     54.0
12   Nilesh     12  67.00     78.0     89.0
13  Prakash     10  50.00     45.0     33.0
14  Kalpesh     12  45.00     78.0     90.0
15   Adarsh     12  90.00     78.0     45.0
16     Raja     10  67.00     58.0     59.0
17  Pritesh      9  56.00     90.0     45.0
18   Mahesh     10  45.00     33.0     36.0
19  Poojesh      8  90.00     99.0     89.0
20    Akash      7  88.00     45.0     67.0

In [55]:
# 7. Use Backward fill(bfill) to fill missing values.

df_bfill = df.fillna(method='bfill')
df_bfill

       Name  Class   Math  Science  English
0      Amit     10  78.00     81.0     88.0
1      Riya     10  72.35     81.0     76.0
2     Sumit     11  65.00     70.0     90.0
3     Pooja     11  88.00     89.0     90.0
4       Raj     12  55.00     92.0     65.0
5     Sneha     12  95.00     92.0     94.0
6    Rajesh      9  99.00     87.0     90.0
7     Mohit     11  67.00     91.0     56.0
8   Krishna     12  90.00     91.0     97.0
9    Mukesh     10  78.00     89.0     70.0
10  Radhika     11  89.00     78.0     87.0
11   Vishal     12  45.00     67.0     54.0
12   Nilesh     12  67.00     78.0     89.0
13  Prakash     10  50.00     45.0     33.0
14  Kalpesh     12  45.00     78.0     90.0
15   Adarsh     12  90.00     78.0     45.0
16     Raja     10  67.00     58.0     59.0
17  Pritesh      9  56.00     90.0     45.0
18   Mahesh     10  45.00     33.0     36.0
19  Poojesh      8  90.00     99.0     89.0
20    Akash      7  88.00     45.0     67.0

In [57]:
# 8. Fill missing Science marks with the median of Science,but keep others unchanged.

df["Science"] = df["Science"].fillna(df["Science"].median())
df

       Name  Class   Math  Science  English
0      Amit     10  78.00     78.0     88.0
1      Riya     10  72.35     81.0     76.0
2     Sumit     11  65.00     70.0      NaN
3     Pooja     11  88.00     89.0     90.0
4       Raj     12  55.00     78.0     65.0
5     Sneha     12  95.00     92.0     94.0
6    Rajesh      9  99.00     87.0     90.0
7     Mohit     11  67.00     91.0     56.0
8   Krishna     12  90.00     91.0     97.0
9    Mukesh     10  78.00     89.0     70.0
10  Radhika     11  89.00     78.0     87.0
11   Vishal     12  45.00     67.0     54.0
12   Nilesh     12  67.00     78.0     89.0
13  Prakash     10  50.00     45.0     33.0
14  Kalpesh     12  45.00     78.0     90.0
15   Adarsh     12  90.00     78.0     45.0
16     Raja     10  67.00     58.0     59.0
17  Pritesh      9  56.00     90.0     45.0
18   Mahesh     10  45.00     33.0     36.0
19  Poojesh      8  90.00     99.0     89.0
20    Akash      7  88.00     45.0     67.0

In [59]:
# 9. If English is missing, fill it with 70.

df["English"] = df["English"].fillna(70)
df

       Name  Class   Math  Science  English
0      Amit     10  78.00     78.0     88.0
1      Riya     10  72.35     81.0     76.0
2     Sumit     11  65.00     70.0     70.0
3     Pooja     11  88.00     89.0     90.0
4       Raj     12  55.00     78.0     65.0
5     Sneha     12  95.00     92.0     94.0
6    Rajesh      9  99.00     87.0     90.0
7     Mohit     11  67.00     91.0     56.0
8   Krishna     12  90.00     91.0     97.0
9    Mukesh     10  78.00     89.0     70.0
10  Radhika     11  89.00     78.0     87.0
11   Vishal     12  45.00     67.0     54.0
12   Nilesh     12  67.00     78.0     89.0
13  Prakash     10  50.00     45.0     33.0
14  Kalpesh     12  45.00     78.0     90.0
15   Adarsh     12  90.00     78.0     45.0
16     Raja     10  67.00     58.0     59.0
17  Pritesh      9  56.00     90.0     45.0
18   Mahesh     10  45.00     33.0     36.0
19  Poojesh      8  90.00     99.0     89.0
20    Akash      7  88.00     45.0     67.0

In [63]:
# 10. Verify that no missing values remain in the dataset after applying fill.

print(df.isna().sum())

print("-------------------")
print('Total missing after cleaning:',df.isna().sum().sum())

Name       0
Class      0
Math       0
Science    0
English    0
dtype: int64
-------------------
Total missing after cleaning: 0

# Q-4: Import Employee.csv file.

In [3]:
import pandas as pd

df = pd.read_csv("Employees_1.csv")
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,NaN,12:42 PM,97308.0,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.0,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.0,11.858,False,Finance
3,Jerry,Male,NaN,1:00 PM,NaN,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# 1. Show True/False matrix where missing values are present.

df.isnull()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True
996,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True
999,True,True,True,True,True,True,True,True

In [4]:
# 2. Find the total number of missing values in each column.

df.isna().sum()

First Name           979
Gender               979
Start Date           981
Last Login Time      978
Salary               979
Bonus %              979
Senior Management    978
Team                 980
dtype: int64

In [79]:
# 3. Delete rows where Department is missing.

df = df.dropna(subset=["Department"])

In [5]:
# 4. Replace missing salaries with the mean salary.

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,NaN,12:42 PM,97308.000000,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.000000,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.000000,11.858,False,Finance
3,Jerry,Male,NaN,1:00 PM,88915.809524,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.000000,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN

In [6]:
# 5. Replace missing experience with the median value of the column.

df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,NaN,12:42 PM,97308.000000,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933.000000,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590.000000,11.858,False,Finance
3,Jerry,Male,NaN,1:00 PM,88915.809524,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004.000000,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,88915.809524,NaN,NaN,NaN

In [ ]:
# 6. Replace missing department with the most frequent department(mode).

mode_dept = df["Department"].mode(0)
df["Department"] = df["Department"].fillna(mode_dept)
df

In [11]:
# 7. Diffrent Fill stretegy.

# -> Fill Salary with mean.

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

# -> Fill Experience with 0.

df["Experience"] = df["Experience"].fillna(0)
df

# -> Fill Department with "Unknown".

df["Department"] = df["Department"].fillna("Unknown")

In [4]:
# 8. Find how many rows have more than 1 missing value.

row_missing_count = df.isna().sum(axis=1)
print(row_missing_count)

0      1
1      1
2      0
3      2
4      0
      ..
995    8
996    8
997    8
998    8
999    8
Length: 1000, dtype: int64

In [6]:
# 9. Custom Conditional fill
# ->If Salary is missing and Department ="IT", fill with 60000.

df.loc[(df["Salary"].isna()) & (df["Department"] == "IT"), "Salary"] = 60000

# ->If Salary is missing and Department="Finance",fill with 58000.

df.loc[(df["Salary"].isna()) & (df["Department"] == "Finance"), "Salary"] = 58000

In [8]:
# 10. Interpolation
# Try Using interpolate() to fill numeric missing values(Salary,Experience)

df[["Salary","Experience"]] = df[["Salary","Experience"]].interpolate()

print(df)

In [9]:
# Handling Duplicates

import pandas as pd

df=pd.DataFrame({
    "Name":['Rahul','Amit','Amit','Priya'],
    "Age":[23,25,25,22],
    "States":["Gujarat","Delhi","Rajsthan","Punjab"]
})

print(df)
print(df.duplicated())
print(df.drop_duplicates())

    Name  Age    States
0  Rahul   23   Gujarat
1   Amit   25     Delhi
2   Amit   25  Rajsthan
3  Priya   22    Punjab
0    False
1    False
2    False
3    False
dtype: bool
    Name  Age    States
0  Rahul   23   Gujarat
1   Amit   25     Delhi
2   Amit   25  Rajsthan
3  Priya   22    Punjab

In [10]:
# Replacing Values

print(df.replace({"Delhi":"New Delhi"}))

    Name  Age     States
0  Rahul   23    Gujarat
1   Amit   25  New Delhi
2   Amit   25   Rajsthan
3  Priya   22     Punjab

In [11]:
# Renaming Columns

print(df.rename(columns={'Name':"Full_Name","Age":'Years'}))

  Full_Name  Years    States
0     Rahul     23   Gujarat
1      Amit     25     Delhi
2      Amit     25  Rajsthan
3     Priya     22    Punjab

In [12]:
# Changing Data Types

print(df['Age'].astype(float))

0    23.0
1    25.0
2    25.0
3    22.0
Name: Age, dtype: float64

# Practice Task:-

Use products.csv file and solve following proble:-

1. Duplicates

->Find how many duplicate rows exist.

->Remove duplicates based on all columns.

->Remove duplicates based only on "ProductName".


2. Rename Columns

->Rename "ProductID"->"ID"

->Rename "ProductName"->"Name"

->Convert all column names to uppercase.


3. Changing Data Types

->"ProductID"->string

->"Price"->int(notice row 107 has "45,000" as string with comma)

In [ ]:
import pandas as pd

df = pd.read_csv("products.csv")

print(df)

# 1. Duplicates

In [16]:
# ->Find how many duplicate rows exist.

duplicates_count = df.duplicated().sum()
print(duplicates_count)

0

In [14]:
# ->Remove duplicates based on all columns.

df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)

    Name  Age    States
0  Rahul   23   Gujarat
1   Amit   25     Delhi
2   Amit   25  Rajsthan
3  Priya   22    Punjab

In [18]:
# ->Remove duplicates based only on "ProductName".

df_unique_products = df.drop_duplicates(subset = ["ProductName"])
print(df_unique_products)

# 2. Rename Columns

In [20]:
# ->Rename "ProductID"->"ID"

print(df.rename(columns = {"ProductID" : "ID"}))

In [ ]:
# ->Rename "ProductName"->"Name"

print(df.rename(columns = {"ProductName" : "Name"}))

In [23]:
# ->Convert all column names to uppercase.

df.columns = df.columns.str.strip().str.upper()
df

    NAME  AGE    STATES
0  Rahul   23   Gujarat
1   Amit   25     Delhi
2   Amit   25  Rajsthan
3  Priya   22    Punjab

In [27]:
# 3. Changing Data Types

# ->"ProductID"->string

print(df["ProductID"].astype(str))

# ->"Price"->int(notice row 107 has "45,000" as string with comma)

df["Price"] = df["Price"].astype(str).str.replace(",","")
df["Price"] = df["Price"].astype(int)
df