# Data Manipulation-

Isme hum data ko modify clean or organize karte hai.

In [18]:
import pandas as pd

df=pd.DataFrame({
    "Name":['Rahul','Aman','Priya'],
    'Marks':[85,90,78]
})
df

    Name  Marks
0  Rahul     85
1   Aman     90
2  Priya     78

In [19]:
df['age'] = [21,23,32]
df['city']=['Jungadh','Botad','America']
df
df.drop(['Marks','age'],axis=1)   #axis = 0 : row, axis = 1 : column

    Name     city
0  Rahul  Jungadh
1   Aman    Botad
2  Priya  America

In [20]:
df=df.drop(['age','city'],axis=1)

In [21]:
df

    Name  Marks
0  Rahul     85
1   Aman     90
2  Priya     78

# 1.Adding and removing columns.

In [22]:
# Add column:df['new_col']=values

# Remove column:df.drop('colname',axis=1,inplace=True)

import pandas as pd

df=pd.DataFrame({
    "Name":['Rahul','Aman','Priya'],
    'Marks':[85,90,78]
})

# add new column
df['Grade']=['B','A','C']
print(df)

# remove column

df.drop('Marks',axis=1,inplace=True)     #OR df = df[df.drop('Marks',axis=1)] 
# print(df)
df

    Name  Marks Grade
0  Rahul     85     B
1   Aman     90     A
2  Priya     78     C

    Name Grade
0  Rahul     B
1   Aman     A
2  Priya     C

In [23]:
import pandas as pd

data = {
    'name':['kuldip','sumit','ankit'],
    'age':[21,22,34]
}

df = pd.DataFrame(data)

df

     name  age
0  kuldip   21
1   sumit   22
2   ankit   34

# 2.Adding Derived columns

In [24]:
# kabhi hume exisiting columns se naya column banana hota hai.

df['Percentage']=(df['age']/100)*100
print(df)

     name  age  Percentage
0  kuldip   21        21.0
1   sumit   22        22.0
2   ankit   34        34.0

# 3.Sorting

In [25]:
# sort_values(by='column')->kisi column ke hisab se sort.

df.sort_values(by='age',ascending=False,inplace=True)
print(df)

     name  age  Percentage
2   ankit   34        34.0
1   sumit   22        22.0
0  kuldip   21        21.0

# 4.Resetting Index

In [7]:
# data filter/sort krne ke bad index bigad jata hai ->reset krna padta hai.

df.reset_index(drop=True,inplace=True)
print(df)

    Name  Marks
0  Rahul     85
1   Aman     90
2  Priya     78

# 5. Setting Index

In [8]:
# kisi column ko index bana sakte ho

df.set_index("Name",inplace=True)
print(df)

       Marks  Percentage
Name
Aman      90        90.0
Rahul     85        85.0
Priya     78        78.0

# Practice Tasks:-



Task-1: Add/Remove Columns

Create a DataFrame:

data={
    "Name":["Rahul","Aman","Priya"],
    "Age":[21,19,22],
    "Marks":[85,92,76]

}

->Add a new column Grade based on Marks:

Marks>=90->A

Marks>=80->B

Else->C

->Remove the Age column.



Task-2:Derived Column

Create a DataFrame:

data={
    "Product":["Pen","Book","Bag],
    "Price":[10,50,500],
    "Quantity":[5,2,1]
    }


->Add a new column Total=Price*Quantity

->Add another column DiscountPrice=90% of Total.



Task-3: Sorting

create DataFrame:

data={
    "Name":["Ravi","Sneha","Kiran"],
    "Age":[25,28,22],
    "Salary":[40000,50000,35000]
}

->Sort by Salary in descending order.

->Sort by Age in ascending order.



Task-4:Restting and setting Index.

create DataFrame:

data={
    "City":["Delhi","Mumbai","Chennai"],
    "Population":[19000000,20000000,10000000]

}

->After sorting by Population, reset the index.

->Set City as the index.


----------------------------------------------------------------------------------------------------------

# Practice Task's Solution:

# Task-1: Add/Remove Columns

In [2]:
# Create a DataFrame:
import pandas as pd

data={ 
        "Name":["Rahul","Aman","Priya"], 
        "Age":[21,19,22], 
        "Marks":[85,92,76]
     }
df = pd.DataFrame(data)
df

# ->Add a new column Grade based on Marks:
# Marks>=90->A
# Marks>=80->B
# Else->C

df["Grade"] = df["Marks"].apply(
    lambda x: "A" if x>=90 else "B" if x >= 80 else "C")

print(df)
# ->Remove the Age column.

    Name  Age  Marks Grade
0  Rahul   21     85     B
1   Aman   19     92     A
2  Priya   22     76     C

# Task-2:Derived Column

In [35]:
# Create a DataFrame:

data={ 
        "Product":["Pen","Book","Bag"], 
        "Price":[10,50,500], 
        "Quantity":[5,2,1]
    }

df = pd.DataFrame(data)
df

# ->Add a new column Total=Price*Quantity

df['Total'] = df["Price"] * df["Quantity"]
df


# ->Add another column DiscountPrice=90% of Total.

df["DiscountPrice"] = (df["Total"]/100)*90
df

  Product  Price  Quantity  Total  DiscountPrice
0     Pen     10         5     50           45.0
1    Book     50         2    100           90.0
2     Bag    500         1    500          450.0

# Task-3: Sorting

In [40]:
# create DataFrame:

data={ "Name":["Ravi","Sneha","Kiran"], 
       "Age":[25,28,22], 
       "Salary":[40000,50000,35000] 
     }

df = pd.DataFrame(data)
df
# ->Sort by Salary in descending order.

df = df.sort_values(by = "Salary", ascending = False)
df
# ->Sort by Age in ascending order.
df.sort_values(by = "Age", ascending = True, inplace = True)
df

    Name  Age  Salary
2  Kiran   22   35000
0   Ravi   25   40000
1  Sneha   28   50000

# Task-4:Restting and setting Index.

In [48]:
# create DataFrame:

data={ 
        "City":["Delhi","Mumbai","Chennai"], 
        "Population":[19000000,20000000,10000000]
    }
df = pd.DataFrame(data)
df

# ->After sorting by Population, reset the index.

df.sort_values(by = "Population",inplace = True)
df

df.reset_index(drop = True, inplace = True)
df

# ->Set City as the index.

df.set_index("City", inplace=True)
df

         Population
City
Chennai    10000000
Delhi      19000000
Mumbai     20000000